import { clsx } from "clsx";
import { extendTailwindMerge } from "tailwind-merge"

const twMerge = extendTailwindMerge({
  extend: {
    theme: {
      text: ["display", "heading", "body", "ui", "label", "data"],
      color: [
        "primary-hover",
        "action",
        "action-hover",
        "action-muted",
        "action-foreground",
        "surface",
        "surface-elevated",
        "surface-raised",
        "surface-chrome",
        "surface-subtle",
        "surface-muted",
        "block",
        "block-subtle",
        "block-border",
        "control",
        "control-hover",
        "control-selected",
        "control-border",
        "island",
        "island-hover",
        "island-selected",
        "island-border",
        "material-liquid",
        "material-vibrant",
        "material-chrome",
        "premium-athens",
        "premium-shark",
        "premium-graphite",
        "premium-blue",
        "premium-indigo",
        "premium-purple",
      ],
      spacing: [
        "micro",
        "tag",
        "item",
        "control",
        "component",
        "card",
        "panel",
        "page",
        "section",
        "control-mini",
        "control-small",
        "target",
        "control-large",
        "layout",
        "control-xl",
        "spacious",
        "island",
        "block",
        "sidebar-inset",
        "app-gutter",
        "content-gutter",
        "app-rail",
        "sidebar-collapsed",
        "sidebar-expanded",
        "search",
        "search-compact",
        "number-field",
        "inspector",
        "menu",
        "popover",
      ],
      shadow: ["block", "material", "premium"],
      radius: ["island", "block", "control", "item"],
      container: [
        "content",
        "readable",
        "form",
        "inspector",
        "detail-value",
        "title",
        "chip",
        "sheet-sm",
        "sheet-md",
        "modal-lg",
        "modal-xl",
        "viewport-safe",
      ],
    },
    classGroups: {
      "max-w": [
        {
          "max-w": [
            "content",
            "readable",
            "form",
            "inspector",
            "detail-value",
            "title",
            "chip",
            "sheet-sm",
            "sheet-md",
            "modal-lg",
            "modal-xl",
            "viewport-safe",
          ],
        },
      ],
      shadow: [{ shadow: ["block", "material", "premium"] }],
      rounded: [{ rounded: ["island", "block", "control", "item"] }],
      duration: [
        {
          duration: [
            "motion-instant",
            "motion-fast",
            "motion",
            "motion-medium",
            "motion-disclosure",
            "motion-slow",
          ],
        },
      ],
      ease: [
        {
          ease: ["motion-standard", "motion-emphasized", "motion-exit"],
        },
      ],
      delay: [{ delay: ["motion-label"] }],
    },
  },
});

export function cn(...inputs) {
  return twMerge(clsx(inputs));
}
