export const executiveDashboardStaticData = Object.freeze({
  title: 'Executive Dashboard',
  periodLabel: 'June 2026',
  audienceLabel: 'Inspo Dental',
  updatedAtLabel: 'Static preview data',
  sourceLabel: 'Manual executive model',
  periodContext: {
    eyebrow: 'Monthly Executive Review',
    title: 'June 2026',
    meta: 'GHL Marketing Pipeline | Dentrix Sync | Data through Jun 24',
  },
  overviewMetrics: [
    {
      id: 'total-production',
      label: 'Total production',
      value: '$67K',
      context: 'Dentrix | 774 visits @ avg $87',
      badge: 'est',
      tone: 'amber',
    },
    {
      id: 'new-bookings-meta',
      label: 'New bookings (Meta)',
      value: '33',
      context: '$6,600 @ $200/booking',
      contextTone: 'green',
      badge: 'GHL live',
      tone: 'green',
    },
    {
      id: 'total-opportunities',
      label: 'Total opportunities',
      value: '3,917',
      context: 'Dentrix pipeline',
      badge: 'GHL live',
      tone: 'green',
    },
  ],
  summary: {
    narrative: 'The month is directionally healthy: reactivation is producing efficient bookings, but treatment acceptance and revenue per visit need leadership attention before the next review.',
    mainWin: 'Reactivation delivered the clearest return with a low acquisition cost and immediate hygiene revenue.',
    mainIssue: 'Treatment handoff is the visible constraint. Bookings are converting, but accepted treatment is lagging the available opportunity.',
    nextFocus: 'Protect the reactivation engine, tighten front-desk handoff, and validate Dentrix revenue attribution before adding more paid acquisition pressure.',
  },
  headlineMetrics: [
    {
      id: 'new-patients',
      label: 'New patients',
      value: '87',
      context: '+12 vs previous month',
      status: 'On track',
      tone: 'green',
    },
    {
      id: 'booked-visits',
      label: 'Booked visits',
      value: '83',
      context: '95% of target',
      status: 'Watch',
      tone: 'amber',
    },
    {
      id: 'estimated-roi',
      label: 'Estimated ROI',
      value: '5.1x',
      context: 'Reactivation day-one return',
      status: 'Healthy',
      tone: 'green',
    },
    {
      id: 'treatment-accepted',
      label: 'Treatment accepted',
      value: '8%',
      context: 'Below handoff target',
      status: 'Below',
      tone: 'rose',
    },
  ],
  intelligence: [
    {
      id: 'worked',
      label: 'Worked',
      tone: 'green',
      items: [
        { figure: '33', text: 'Meta leads booked from 122 total - 27% conversion' },
        { figure: '$97', text: 'cost per booked patient from Meta (calculable now)' },
        { figure: '$39', text: 'cost per reactivated hygiene patient - 5.1x day-one return' },
      ],
    },
    {
      id: 'failed',
      label: "Didn't work",
      tone: 'rose',
      items: [
        { figure: '89/122', text: 'Meta leads stuck in "New Lead" - never contacted or converted' },
        { figure: '$0', text: 'no revenue-per-campaign data - spend vs outcome unmeasurable by ad' },
        { figure: '4/50', text: 'reactivated patients who accepted treatment beyond hygiene' },
      ],
    },
    {
      id: 'next',
      label: 'Next',
      tone: 'blue',
      items: [
        { figure: '89', text: 'stale Meta leads need a follow-up sequence, not manual outreach' },
        { figure: '+$78-125K', text: 'unscheduled Dentrix treatment ($312K EV) - automate follow-up' },
        { figure: 'Fix', text: 'hygiene-to-treatment handoff after reactivation visits' },
      ],
    },
  ],
  financialHealth: [
    {
      id: 'revenue-per-visit',
      label: 'Revenue per visit',
      value: '$87',
      helper: 'Target starts at $200',
      progress: 43,
      tone: 'amber',
      status: 'Low',
    },
    {
      id: 'booking-rate',
      label: 'Booking rate',
      value: '95%',
      helper: 'Booked vs monthly goal',
      progress: 95,
      tone: 'amber',
      status: 'Watch',
    },
    {
      id: 'treatment-rate',
      label: 'Treatment acceptance',
      value: '12%',
      helper: 'Estimated accepted treatment',
      progress: 24,
      tone: 'amber',
      status: 'Watch',
    },
    {
      id: 'capacity-fill',
      label: 'Capacity fill',
      value: '61%',
      helper: 'Healthy but not saturated',
      progress: 61,
      tone: 'green',
      status: 'Healthy',
    },
  ],
  unitEconomics: [
    { id: 'reactivation-cac', label: 'Reactivation CAC', value: '$39', helper: 'per booked patient', tone: 'green' },
    { id: 'meta-cac', label: 'Meta CAC', value: '$97', helper: 'per booked patient', tone: 'amber' },
    { id: 'first-visit-value', label: 'First visit value', value: '$200', helper: 'average ticket assumption', tone: 'blue' },
  ],
  channelMix: [
    { id: 'reactivation', label: 'Reactivation', value: 50, share: '43%', tone: 'green' },
    { id: 'meta', label: 'Meta leads', value: 33, share: '28%', tone: 'purple' },
    { id: 'recall', label: 'Returning / recall', value: 33, share: '28%', tone: 'blue' },
  ],
  funnel: [
    { id: 'enrolled', label: 'Enrolled', value: 648, conversion: '100%', progress: 100, tone: 'blue' },
    { id: 'reached', label: 'Reached', value: 627, conversion: '97%', progress: 97, tone: 'blue' },
    { id: 'replied', label: 'Replied', value: 85, conversion: '13%', progress: 34, tone: 'purple' },
    { id: 'booked', label: 'Booked hygiene', value: 50, conversion: '59% of replies', progress: 24, tone: 'green' },
    { id: 'accepted', label: 'Treatment accepted', value: 4, conversion: '8%', progress: 10, tone: 'rose' },
  ],
  decisions: [
    {
      id: 'handoff',
      title: 'Treatment handoff audit',
      recommendation: 'Review attended reactivation visits before changing acquisition budget.',
      owner: 'Practice manager',
      due: 'Next weekly review',
      tone: 'amber',
    },
    {
      id: 'revenue-attribution',
      title: 'Revenue attribution confidence',
      recommendation: 'Connect Dentrix revenue mapping before presenting ROI as final.',
      owner: 'Agency data lead',
      due: 'Before monthly close',
      tone: 'blue',
    },
    {
      id: 'scale-reactivation',
      title: 'Scale reactivation cautiously',
      recommendation: 'Keep the channel active, but hold budget increases until treatment acceptance improves.',
      owner: 'Account lead',
      due: 'After handoff audit',
      tone: 'green',
    },
  ],
})
