export const executiveDashboardStaticData = Object.freeze({
  title: 'Executive Dashboard',
  periodLabel: 'June 2026',
  audienceLabel: 'Inspo Dental',
  updatedAtLabel: 'Static preview data',
  sourceLabel: 'Manual executive model',
  periodContext: {
    eyebrow: 'Monthly Executive Review',
    title: 'June 2026',
    meta: 'GHL Marketing Pipeline | Dentrix Sync | Data through Jun 24',
  },
  overviewMetrics: [
    {
      id: 'total-production',
      label: 'Total production',
      value: '$67K',
      context: 'Dentrix | 774 visits @ avg $87',
      badge: 'est',
      tone: 'amber',
    },
    {
      id: 'new-bookings',
      label: 'New bookings',
      value: '—',
      context: 'Current month',
      badge: 'GHL live',
      tone: 'green',
    },
    {
      id: 'total-opportunities',
      label: 'Total opportunities',
      value: '3,917',
      context: 'Dentrix pipeline',
      badge: 'GHL live',
      tone: 'green',
    },
  ],
  summary: {
    narrative: 'The month is directionally healthy: reactivation is producing efficient bookings, but treatment acceptance and revenue per visit need leadership attention before the next review.',
    mainWin: 'Reactivation delivered the clearest return with a low acquisition cost and immediate hygiene revenue.',
    mainIssue: 'Treatment handoff is the visible constraint. Bookings are converting, but accepted treatment is lagging the available opportunity.',
    nextFocus: 'Protect the reactivation engine, tighten front-desk handoff, and validate Dentrix revenue attribution before adding more paid acquisition pressure.',
  },
  headlineMetrics: [
    {
      id: 'new-patients',
      label: 'New patients',
      value: '87',
      context: '+12 vs previous month',
      status: 'On track',
      tone: 'green',
    },
    {
      id: 'booked-visits',
      label: 'Booked visits',
      value: '83',
      context: '95% of target',
      status: 'Watch',
      tone: 'amber',
    },
    {
      id: 'estimated-roi',
      label: 'Estimated ROI',
      value: '5.1x',
      context: 'Reactivation day-one return',
      status: 'Healthy',
      tone: 'green',
    },
    {
      id: 'treatment-accepted',
      label: 'Treatment accepted',
      value: '8%',
      context: 'Below handoff target',
      status: 'Below',
      tone: 'rose',
    },
  ],
  intelligence: [
    {
      id: 'worked',
      label: 'Worked',
      tone: 'green',
      items: [
        { figure: '33', text: 'Meta leads booked from 122 total - 27% conversion' },
        { figure: '$97', text: 'cost per booked patient from Meta (calculable now)' },
        { figure: '$39', text: 'cost per reactivated hygiene patient - 5.1x day-one return' },
      ],
    },
    {
      id: 'failed',
      label: "Didn't work",
      tone: 'rose',
      items: [
        { figure: '89/122', text: 'Meta leads stuck in "New Lead" - never contacted or converted' },
        { figure: '$0', text: 'no revenue-per-campaign data - spend vs outcome unmeasurable by ad' },
        { figure: '4/50', text: 'reactivated patients who accepted treatment beyond hygiene' },
      ],
    },
    {
      id: 'next',
      label: 'Next',
      tone: 'blue',
      items: [
        { figure: '89', text: 'stale Meta leads need a follow-up sequence, not manual outreach' },
        { figure: '+$78-125K', text: 'unscheduled Dentrix treatment ($312K EV) - automate follow-up' },
        { figure: 'Fix', text: 'hygiene-to-treatment handoff after reactivation visits' },
      ],
    },
  ],
  financialHealth: [
    {
      id: 'production-day',
      label: 'Production / day',
      value: '$87',
      suffix: '/visit',
      status: 'Low',
      tone: 'amber',
      marker: 9,
      targetMarker: 43,
      goodStart: 43,
      goodEnd: 78,
      rangeLabels: ['$0', '$200+ target/visit', '$600'],
    },
    {
      id: 'collections-ratio',
      label: 'Collections ratio',
      value: '95%',
      suffix: 'est',
      status: 'Watch',
      tone: 'amber',
      marker: 72,
      targetMarker: 85,
      goodStart: 84,
      goodEnd: 100,
      rangeLabels: ['85%', '98% target', '100%'],
    },
    {
      id: 'ar-90-days',
      label: 'A/R > 90 days',
      value: '12%',
      suffix: 'est',
      status: 'Watch',
      tone: 'amber',
      marker: 59,
      targetMarker: 50,
      goodStart: 0,
      goodEnd: 50,
      badStart: 75,
      badEnd: 100,
      rangeLabels: ['0%', 'under 10%', '20%'],
    },
    {
      id: 'overhead',
      label: 'Overhead',
      value: '61%',
      suffix: 'est',
      status: 'Healthy',
      tone: 'green',
      marker: 43,
      targetMarker: 50,
      goodStart: 0,
      goodEnd: 50,
      rangeLabels: ['50%', 'under 63%', '80%'],
    },
    {
      id: 'marketing-percent',
      label: 'Marketing % of coll.',
      value: '3.6%',
      status: 'Room',
      tone: 'blue',
      marker: 24,
      targetMarker: 53,
      goodStart: 24,
      goodEnd: 79,
      rangeLabels: ['0%', '8-12% growth', '15%'],
    },
  ],
  financialHealthNote: 'Production/day based on Dentrix "New Booking" stage: 774 visits @ $60,400 recorded value - likely partial field population. Collections, overhead, A/R marked estimated until Dentrix billing export is connected.',
  unitEconomics: {
    ratio: {
      label: 'Patient value : cost to acquire (blended)',
      value: '51',
      suffix: ':1',
      summary: "Every $1 spent acquiring a patient returns $51 in lifetime revenue. Above 7:1 means there's room to invest more in growth.",
      marker: 97,
      rangeLabels: ['3:1 floor', '7:1 healthy', 'you · 51:1 →'],
    },
    acquisitionCosts: [
      {
        id: 'meta-cac',
        label: 'Meta CAC (calculable)',
        value: '$97',
        detail: '$3,200 spend ÷ 33 booked',
        helper: '$200 hygiene → 2× first-visit return',
        tone: 'amber',
      },
      {
        id: 'reactivation-cac',
        label: 'Reactivation CAC',
        value: '$58',
        detail: 'campaign cost ÷ 50 booked',
        helper: '$200 hygiene → 3.4× first-visit return',
        tone: 'green',
      },
    ],
    metrics: [
      {
        id: 'unscheduled-treatment',
        label: 'Unscheduled treatment pipeline',
        badge: 'EV · GHL',
        value: '$312K',
        helper: 'Diagnosed, quoted, not yet booked',
        emphasis: 'not yet booked',
        tone: 'purple',
        featured: true,
      },
      {
        id: 'system-roi',
        label: 'System ROI since install',
        badge: 'VFI · GHL',
        value: '7.9×',
        helper: '$146K earned vs $18.5K system cost',
        emphasis: '$18.5K system cost',
        tone: 'blue',
      },
      {
        id: 'first-visit-value',
        label: 'Avg first visit (reactivation)',
        badge: 'FTV · GHL',
        value: '$200',
        helper: 'Hygiene cleaning confirmed avg ticket',
        emphasis: 'confirmed avg ticket',
        tone: 'blue',
      },
      {
        id: 'lifetime-value',
        label: 'Avg patient lifetime value',
        badge: 'LTV · GHL',
        value: '$9.4K',
        helper: 'Cosmetic patients ~$27.8K',
        emphasis: '~$27.8K',
        tone: 'blue',
      },
    ],
  },
  leadConversion: {
    bookingsBySource: {
      total: 116,
      badge: 'live · GHL',
      sources: [
        { id: 'reactivation', label: 'Reactivation', value: 50, share: '43%', tone: 'green' },
        { id: 'meta', label: 'Meta leads', value: 33, share: '28%', tone: 'purple' },
        { id: 'recall', label: 'Returning / recall', value: 33, share: '28%', tone: 'blue' },
      ],
      revenue: [
        { id: 'reactivation', label: 'Reactivation · hygiene', value: '$10,000' },
        { id: 'meta', label: 'Meta leads · new', value: '$6,600' },
        { id: 'other', label: 'Other / Dentrix', value: '~$50K est' },
      ],
    },
    reactivationFunnel: {
      badge: 'GHL live',
      note: 'avg ticket $200',
      stages: [
        { id: 'enrolled', label: 'Enrolled', value: 648, progress: 100, tone: 'blue' },
        { id: 'reached', label: 'Reached', value: 627, progress: 97, conversion: '97%', conversionTone: 'green', tone: 'blue' },
        { id: 'replied', label: 'Replied', value: 85, progress: 34, conversion: '13%', conversionTone: 'green', tone: 'purple' },
        { id: 'booked', label: 'Booked hygiene', value: 50, progress: 24, conversion: '59% of replies · $10K rev', conversionTone: 'green', tone: 'purple' },
        { id: 'accepted', label: 'Treatment accepted', value: 4, progress: 10, conversion: '8% — handoff gap', conversionTone: 'rose', tone: 'green' },
      ],
      footer: 'CAC: $39/patient · $200 avg ticket · 5.1× day-one return',
      footerEmphasis: '5.1× day-one return',
    },
    metaPaidAds: {
      badge: 'partial data',
      flow: [
        { id: 'spend', value: '$3.2K', label: 'Spend' },
        { id: 'leads', value: '122', label: 'Leads' },
        { id: 'booked', value: '33', label: 'Booked', helper: '$97 CAC', tone: 'green' },
      ],
      cacByChannel: [
        { id: 'reactivation', label: 'Reactivation', value: '$39', helper: '$200 ticket · 5.1× return', tone: 'green' },
        { id: 'meta-booked', label: 'Meta (booked)', value: '$97', helper: '$200 ticket · 2× return', tone: 'amber' },
        { id: 'meta-shown', label: 'Meta (shown)', value: '$26', helper: 'per lead, not per patient', tone: 'neutral' },
      ],
      signals: [
        { id: 'spend', label: '✓ spend', tone: 'green' },
        { id: 'leads', label: '✓ leads', tone: 'green' },
        { id: 'bookings', label: '✓ bookings (GHL)', tone: 'green' },
        { id: 'roi', label: '✕ per-campaign ROI', tone: 'rose' },
        { id: 'utm', label: '✕ UTM', tone: 'rose' },
      ],
      missing: 'which campaign produced which booked patient. Need UTM or agency report to optimize ad spend by creative.',
    },
  },
  decisions: [
    {
      id: 'stale-meta-leads',
      title: 'Follow up on the 89 stale Meta leads?',
      evidence: '89 of 122 Meta leads are stuck in "New Lead" at $0 value. At Meta\'s current conversion rate, ~24 of them would book if touched.',
      emphasis: '$0 value',
      recommendation: 'Build a short automated sequence for new leads in GHL. These are paid for — leaving them idle is direct waste.',
      owner: 'Roman + Matt',
      due: '2 weeks',
      outcome: '~$4.8K',
      tone: 'green',
    },
    {
      id: 'unscheduled-treatment-follow-up',
      title: 'Automate unscheduled-treatment follow-up?',
      evidence: '$312K diagnosed, unbooked. 25–40% recoverable in 90 days with systematic follow-up.',
      emphasis: '25–40% recoverable in 90 days',
      recommendation: 'Yes — highest-return build on the roadmap. Pull Dentrix unscheduled list and build GHL sequence next sprint.',
      owner: 'Roman + Matt',
      due: '30d',
      outcome: '+$78–125K',
      tone: 'green',
    },
    {
      id: 'per-campaign-attribution',
      title: 'Get per-campaign attribution from Meta agency?',
      evidence: '$3.2K/mo spent. You know total cost per booked patient ($97) but not which campaign or creative is performing.',
      emphasis: 'not which campaign or creative is performing',
      recommendation: 'Request UTM setup from the agency. Without it, the budget can\'t be optimized — only increased or cut.',
      owner: 'Matt',
      due: '2 weeks',
      outcome: 'unlocks optimization',
      tone: 'green',
    },
  ],
  footerNote: {
    liveLabel: 'Live data',
    liveText: '(GHL): Marketing pipeline — 122 opps, 89 new leads, 33 booked @ $6,600. Dentrix pipeline — 3,917 opps, 774 in "New Booking" @ $60,400 recorded. Reactivation — 648 enrolled, 50 booked, $200 avg hygiene ticket.',
    estimatedLabel: 'Estimated:',
    estimatedText: 'total production, collections ratio, overhead, A/R — need Dentrix billing export connected. Benchmarks: ADA, Levin Group, Dental Economics.',
  },
})
