import { CLIENT_STATUSES, CLIENT_TYPES } from '../../../entities/client'
import { CLIENT_INVITATION_STATUSES } from '../../../entities/client-invitation'
import {
  CLIENT_FILE_LINK_STATUSES,
  CLIENT_FILE_LINK_TYPES,
} from '../../../entities/client-file-link'
import { CLIENT_MEMBERSHIP_ROLES } from '../../../entities/client-membership'
import {
  CLIENT_REQUEST_STATUSES,
  CLIENT_REQUEST_TYPES,
} from '../../../entities/client-request'
import {
  CLIENT_WORK_ITEM_PUBLISH_STATES,
  CLIENT_WORK_ITEM_STATUSES,
} from '../../../entities/client-work-item'
import {
  CLINIC_ACQUISITION_CHANNELS,
  CLINIC_PROFILE_SPECIALTIES,
  CLINIC_SERVICE_LINE_STATUSES,
} from '../../../entities/clinic'
import { DASHBOARD_LINK_STATUSES, DASHBOARD_PROVIDERS } from '../../../entities/dashboard-link'
import {
  NEEDED_ACTION_PRIORITIES,
  NEEDED_ACTION_STATUSES,
  NEEDED_ACTION_TYPES,
} from '../../../entities/needed-from-client'
import {
  PERFORMANCE_CHANNELS,
  PERFORMANCE_DASHBOARD_STATUSES,
  PERFORMANCE_DATA_CONFIDENCE,
  PERFORMANCE_DATA_MODES,
  PERFORMANCE_GOAL_STATUSES,
  PERFORMANCE_INSIGHT_SEVERITIES,
  PERFORMANCE_METRIC_STATUSES,
  PERFORMANCE_NEXT_STEP_PRIORITIES,
  PERFORMANCE_SERVICE_TYPES,
  PERFORMANCE_TREND_GRANULARITIES,
} from '../../../entities/performance-dashboard'
import { USER_ROLES } from '../../../entities/profile'
import { REPORT_STATUSES } from '../../../entities/report'
import { TASK_STATUSES } from '../../../entities/task'
import { CLIENT_UPDATE_TYPES, VISIBILITY } from '../../../entities/update'

export const SEED_IDS = Object.freeze({
  AGENCY_GROWTHLAB: '11111111-1111-4111-8111-111111111111',
  CLIENT_GREEN_DENTAL: '22222222-2222-4222-8222-222222222222',
  CALL_BOOKING_EMERGENCY: '38383838-3838-4838-9838-383838383838',
  CALL_BOOKING_IMPLANTS: '39393939-3939-4939-9939-393939393939',
  CLINIC_LOCATION_GREEN_MAIN: '29292929-2929-4929-8929-292929292929',
  CLINIC_PROFILE_GREEN: '30303030-3030-4030-9030-303030303030',
  CLINIC_ACQUISITION_EMERGENCY_GOOGLE: '35353535-3535-4535-9535-353535353535',
  CLINIC_ACQUISITION_IMPLANTS_GOOGLE: '36363636-3636-4636-9636-363636363636',
  CLINIC_ACQUISITION_WHITENING_META: '37373737-3737-4737-9737-373737373737',
  CLINIC_SERVICE_EMERGENCY_DENTAL: '31313131-3131-4131-9131-313131313131',
  CLINIC_SERVICE_IMPLANTS: '32323232-3232-4232-9232-323232323232',
  CLINIC_SERVICE_WHITENING: '34343434-3434-4434-9434-343434343434',
  CLIENT_INVITATION_GREEN: '19191919-1919-4919-8919-191919191919',
  CLIENT_NORTHSTAR_DENTAL: '23232323-2323-4323-8323-232323232323',
  CLIENT_WORK_GA4_CONVERSION: '24242424-2424-4424-8424-242424242424',
  CLIENT_WORK_ARCHIVED_LAUNCH: '28282828-2828-4828-8828-282828282828',
  CLIENT_WORK_INTERNAL_DRAFT: '26262626-2626-4626-8626-262626262626',
  CLIENT_WORK_MONTHLY_REPORT: '25252525-2525-4525-8525-252525252525',
  CLIENT_WORK_REVIEW_CREATIVES: '21212121-2121-4121-8121-212121212121',
  CLIENT_WORK_STANDALONE_SEO: '27272727-2727-4727-8727-272727272727',
  FILE_BRAND_ASSETS: '41414141-4141-4141-8141-414141414141',
  FILE_CREATIVE_BATCH: '42424242-4242-4242-8242-424242424242',
  FILE_INITIAL_CAMPAIGN_ARCHIVE: '40404040-4040-4040-8040-404040404040',
  FILE_INTERNAL_TRACKING: '43434343-4343-4343-8343-434343434343',
  FILE_REPORT_PDF: '45454545-4545-4545-8545-454545454545',
  FILE_SHARED_DRIVE: '46464646-4646-4646-8646-464646464646',
  CLIENT_REQUEST_LANDING_VARIANT: '49494949-4949-4949-8949-494949494949',
  CLIENT_REQUEST_COPY_CHANGE: '50505050-5050-4050-9050-505050505050',
  MEMBERSHIP_CLIENT_GREEN: '18181818-1818-4818-8818-181818181818',
  MEMBERSHIP_TEAM_GREEN: '17171717-1717-4717-8717-171717171717',
  DASHBOARD_GREEN_APRIL: '33333333-3333-4333-8333-333333333333',
  NEEDED_CREATIVE_APPROVAL: '55555555-5555-4555-8555-555555555555',
  NEEDED_OFFER_DETAILS: '44444444-4444-4444-8444-444444444444',
  PERFORMANCE_GREEN_APRIL: '20260401-aaaa-4aaa-8aaa-202604010001',
  PERFORMANCE_GREEN_ARCHIVED_MARCH: '20260301-aaaa-4aaa-8aaa-202603010001',
  PERFORMANCE_GREEN_DRAFT_MAY: '20260501-aaaa-4aaa-8aaa-202605010001',
  PERFORMANCE_NORTHSTAR_APRIL: '20260401-bbbb-4bbb-8bbb-202604010002',
  PROFILE_ADMIN_GROWTHLAB: '77777777-7777-4777-8777-777777777777',
  PROFILE_CLIENT_GREEN: '66666666-6666-4666-8666-666666666666',
  PROFILE_TEAM_MIA: 'abababab-abab-4bab-8bab-abababababab',
  PROJECT_CAMPAIGN_SETUP: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  PROJECT_LANDING_PAGE: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
  PROJECT_REPORTING: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
  REPORT_APRIL_2026: 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',
  REPUTATION_GREEN_MAIN: '51515151-5151-4151-9151-515151515151',
  TASK_GA4_CONVERSION: 'ffffffff-ffff-4fff-8fff-ffffffffffff',
  TASK_INTERNAL_DEBUGGING: '123e4567-e89b-42d3-a456-426614174001',
  TASK_MONTHLY_REPORT: '123e4567-e89b-42d3-a456-426614174000',
  TASK_REVIEW_CREATIVES: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
  UPDATE_INTERNAL_TRACKING: '123e4567-e89b-42d3-a456-426614174003',
  UPDATE_REPORT_PUBLISHED: '47474747-4747-4747-8747-474747474747',
  UPDATE_CREATIVE_LAUNCH: '48484848-4848-4848-8848-484848484848',
  UPDATE_WEEKLY_MAY_8: '123e4567-e89b-42d3-a456-426614174002',
  USER_ADMIN_GROWTHLAB: '99999999-9999-4999-8999-999999999999',
  USER_CLIENT_GREEN: '88888888-8888-4888-8888-888888888888',
  USER_TEAM_MIA: 'bcbcbcbc-bcbc-4cbc-8cbc-bcbcbcbcbcbc',
})

function addDays(date, days) {
  const nextDate = new Date(date)
  nextDate.setUTCDate(nextDate.getUTCDate() + days)
  return nextDate
}

function formatIsoDate(date) {
  return date.toISOString().slice(0, 10)
}

function formatShortDate(date) {
  return date.toISOString().slice(5, 10)
}

function getReactivationTouchPlan(dayIndex, weekIndex) {
  if (weekIndex <= 2) {
    return {
      email: dayIndex % 3 === 0 ? 13 : 0,
      manager_calls: 0,
      sms: dayIndex % 4 === 0 ? 13 : 14,
    }
  }

  if (weekIndex <= 7) {
    const peakBoost = weekIndex === 6 || weekIndex === 7 ? 8 : 0

    return {
      email: 25 + peakBoost,
      manager_calls: weekIndex >= 4 ? 12 + peakBoost : 0,
      sms: 27 + peakBoost,
    }
  }

  if (weekIndex <= 13) {
    const spike = weekIndex === 11 ? 12 : 0

    return {
      email: 27 + spike,
      manager_calls: 18 + spike,
      sms: 29 + (spike ? 0 : 0),
    }
  }

  return {
    email: Math.max(5, 24 - (weekIndex - 13) * 8),
    manager_calls: Math.max(0, 18 - (weekIndex - 13) * 7),
    sms: Math.max(0, 22 - (weekIndex - 13) * 8),
  }
}

function createGreenDentalReactivationCampaignExecution() {
  const startDate = new Date(Date.UTC(2026, 5, 1))
  const activitySeries = []
  let cumulativeBookings = 0
  let calendarOffset = 0

  while (activitySeries.length < 75) {
    const date = addDays(startDate, calendarOffset)
    calendarOffset += 1

    const dayOfWeek = date.getUTCDay()

    if (dayOfWeek === 0 || dayOfWeek === 6) {
      continue
    }

    const dayIndex = activitySeries.length
    const weekIndex = Math.floor(dayIndex / 5) + 1
    const touches = getReactivationTouchPlan(dayIndex, weekIndex)
    const bookingLift = weekIndex <= 2
      ? 0.1
      : weekIndex <= 7
        ? 0.45
        : weekIndex <= 13
          ? 0.65
          : 0.35

    cumulativeBookings = Math.min(40, cumulativeBookings + bookingLift)
    activitySeries.push({
      ...touches,
      cumulative_bookings: Number(cumulativeBookings.toFixed(1)),
      date: formatIsoDate(date),
      label: formatShortDate(date),
    })
  }

  return {
    activity_series: activitySeries,
    assumptions: [
      'Business days only. Dates are illustrative and assume a Monday June 1, 2026 start.',
      'Volumes are realistic planning estimates after approximately 5% touch attrition.',
    ],
    kpis: [
      {
        display_order: 10,
        id: 'reactivation-kpi-patients',
        label: 'Patients',
        tone: 'neutral',
        value: 804,
      },
      {
        display_order: 20,
        id: 'reactivation-kpi-sms',
        label: 'SMS sent',
        tone: 'blue',
        value: '~1,660',
      },
      {
        display_order: 30,
        id: 'reactivation-kpi-emails',
        label: 'Emails sent',
        tone: 'green',
        value: '~1,580',
      },
      {
        display_order: 40,
        id: 'reactivation-kpi-calls',
        label: 'Manager calls',
        tone: 'orange',
        value: '~870',
      },
      {
        display_order: 50,
        id: 'reactivation-kpi-bookings',
        label: 'Projected bookings',
        tone: 'amber',
        value: '38-42',
      },
      {
        display_order: 60,
        id: 'reactivation-kpi-duration',
        label: 'Duration',
        tone: 'neutral',
        value: '~15 wk',
      },
    ],
    left_axis_label: 'Touches per day',
    right_axis_label: 'Cumulative bookings',
    subtitle: 'Planned reactivation touches across SMS, email, and manager calls with cumulative booking projection.',
    title: 'Patient Reactivation Campaign Plan',
    tracks: [
      {
        display_order: 10,
        end_week: 2,
        id: 'track-r-pilot',
        label: 'Track R - pilot (wk 1-2)',
        start_week: 1,
        tone: 'orange',
      },
      {
        display_order: 20,
        end_week: 7,
        id: 'track-a-gentle',
        label: 'Track A - gentle reactivation (wk 2-7)',
        start_week: 2,
        tone: 'green',
      },
      {
        display_order: 30,
        end_week: 13,
        id: 'track-b-core',
        label: 'Track B - core reactivation (wk 5-13)',
        start_week: 5,
        tone: 'blue',
      },
      {
        display_order: 40,
        end_week: 15,
        id: 'track-c-winback',
        label: 'Track C - win-back (wk 10-15)',
        start_week: 10,
        tone: 'purple',
      },
    ],
  }
}

export const portalSeedData = Object.freeze({
  activity_events: [],
  client_invitations: [
    {
      accepted_at: null,
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-01T09:00:00.000Z',
      email: 'new.client@greendental.example',
      id: SEED_IDS.CLIENT_INVITATION_GREEN,
      invited_by: SEED_IDS.PROFILE_ADMIN_GROWTHLAB,
      name: 'New Green Dental Client',
      role: CLIENT_MEMBERSHIP_ROLES.VIEWER,
      status: CLIENT_INVITATION_STATUSES.PENDING,
      token: 'invite-green-dental-client',
      updated_at: '2026-05-01T09:00:00.000Z',
    },
  ],
  client_memberships: [
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-01T09:00:00.000Z',
      id: SEED_IDS.MEMBERSHIP_CLIENT_GREEN,
      role: CLIENT_MEMBERSHIP_ROLES.OWNER,
      updated_at: '2026-05-01T09:00:00.000Z',
      user_id: SEED_IDS.USER_CLIENT_GREEN,
    },
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-01T09:00:00.000Z',
      id: SEED_IDS.MEMBERSHIP_TEAM_GREEN,
      role: CLIENT_MEMBERSHIP_ROLES.VIEWER,
      updated_at: '2026-05-01T09:00:00.000Z',
      user_id: SEED_IDS.USER_TEAM_MIA,
    },
  ],
  client_requests: [
    {
      agency_response: '',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-11T10:00:00.000Z',
      description: 'Please prepare one more landing page variant focused on emergency appointments before we scale the next ad set.',
      desired_due_date: '2026-05-24',
      id: SEED_IDS.CLIENT_REQUEST_LANDING_VARIANT,
      project_id: SEED_IDS.PROJECT_LANDING_PAGE,
      reference_link: 'https://example.com/emergency-landing-reference',
      request_type: CLIENT_REQUEST_TYPES.NEW_WORK,
      response_history: [
        {
          created_at: '2026-05-11T10:00:00.000Z',
          created_by: SEED_IDS.USER_CLIENT_GREEN,
          metadata: {
            actor_role: USER_ROLES.CLIENT_USER,
            title: 'Create emergency landing page variant',
          },
          type: 'client_submitted',
        },
      ],
      status: CLIENT_REQUEST_STATUSES.SUBMITTED,
      submitted_by: SEED_IDS.USER_CLIENT_GREEN,
      submitted_by_name: 'Sarah Johnson',
      title: 'Create emergency landing page variant',
      updated_at: '2026-05-11T10:00:00.000Z',
    },
    {
      agency_response: 'We accepted this change and will include it in the next creative revision.',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-07T11:00:00.000Z',
      description: 'Please soften the discount language in the whitening ad before it goes live.',
      desired_due_date: '2026-05-14',
      id: SEED_IDS.CLIENT_REQUEST_COPY_CHANGE,
      project_id: SEED_IDS.PROJECT_CAMPAIGN_SETUP,
      reference_link: '',
      request_type: CLIENT_REQUEST_TYPES.CHANGE_REQUEST,
      response_history: [
        {
          created_at: '2026-05-07T11:00:00.000Z',
          created_by: SEED_IDS.USER_CLIENT_GREEN,
          metadata: {
            actor_role: USER_ROLES.CLIENT_USER,
            title: 'Adjust whitening ad language',
          },
          type: 'client_submitted',
        },
      ],
      status: CLIENT_REQUEST_STATUSES.ACCEPTED,
      submitted_by: SEED_IDS.USER_CLIENT_GREEN,
      submitted_by_name: 'Sarah Johnson',
      title: 'Adjust whitening ad language',
      updated_at: '2026-05-08T11:00:00.000Z',
    },
  ],
  client_work_items: [
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-08T09:00:00.000Z',
      id: SEED_IDS.CLIENT_WORK_REVIEW_CREATIVES,
      last_reviewed_at: '2026-05-08T09:00:00.000Z',
      project_id: SEED_IDS.PROJECT_CAMPAIGN_SETUP,
      publish_state: CLIENT_WORK_ITEM_PUBLISH_STATES.PUBLISHED,
      published_at: '2026-05-08T09:15:00.000Z',
      published_by: SEED_IDS.USER_ADMIN_GROWTHLAB,
      sort_order: 10,
      source_task_id: SEED_IDS.TASK_REVIEW_CREATIVES,
      status: CLIENT_WORK_ITEM_STATUSES.WAITING_CLIENT,
      summary: 'The second creative batch is ready for review. Approval is needed before the next ad test can launch.',
      target_date: '2026-05-09',
      title: 'Review new ad creatives',
      updated_at: '2026-05-08T09:15:00.000Z',
    },
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-08T09:00:00.000Z',
      id: SEED_IDS.CLIENT_WORK_GA4_CONVERSION,
      last_reviewed_at: '2026-05-08T09:00:00.000Z',
      project_id: SEED_IDS.PROJECT_REPORTING,
      publish_state: CLIENT_WORK_ITEM_PUBLISH_STATES.PUBLISHED,
      published_at: '2026-05-08T09:20:00.000Z',
      published_by: SEED_IDS.USER_ADMIN_GROWTHLAB,
      sort_order: 20,
      source_task_id: SEED_IDS.TASK_GA4_CONVERSION,
      status: CLIENT_WORK_ITEM_STATUSES.IN_PROGRESS,
      summary: 'Conversion tracking is being connected so future reports can show lead quality and campaign impact more clearly.',
      target_date: '2026-05-11',
      title: 'Connect GA4 conversion event',
      updated_at: '2026-05-08T09:20:00.000Z',
    },
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-08T09:00:00.000Z',
      id: SEED_IDS.CLIENT_WORK_MONTHLY_REPORT,
      last_reviewed_at: null,
      project_id: SEED_IDS.PROJECT_REPORTING,
      publish_state: CLIENT_WORK_ITEM_PUBLISH_STATES.READY_FOR_REVIEW,
      published_at: null,
      published_by: null,
      sort_order: 30,
      source_task_id: SEED_IDS.TASK_MONTHLY_REPORT,
      status: CLIENT_WORK_ITEM_STATUSES.IN_PROGRESS,
      summary: 'April reporting is being prepared with a concise summary of results, wins, blockers, and next actions.',
      target_date: '2026-05-12',
      title: 'Prepare monthly report',
      updated_at: '2026-05-08T09:00:00.000Z',
    },
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-08T08:30:00.000Z',
      id: SEED_IDS.CLIENT_WORK_INTERNAL_DRAFT,
      last_reviewed_at: null,
      project_id: SEED_IDS.PROJECT_REPORTING,
      publish_state: CLIENT_WORK_ITEM_PUBLISH_STATES.DRAFT,
      published_at: null,
      published_by: null,
      sort_order: 99,
      source_task_id: SEED_IDS.TASK_INTERNAL_DEBUGGING,
      status: CLIENT_WORK_ITEM_STATUSES.NEEDS_ATTENTION,
      summary: 'We are resolving a technical setup issue before exposing this work to the client.',
      target_date: '2026-05-09',
      title: 'Resolve tracking setup issue',
      updated_at: '2026-05-08T08:30:00.000Z',
    },
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-07T10:00:00.000Z',
      id: SEED_IDS.CLIENT_WORK_STANDALONE_SEO,
      last_reviewed_at: '2026-05-07T10:00:00.000Z',
      project_id: SEED_IDS.PROJECT_LANDING_PAGE,
      publish_state: CLIENT_WORK_ITEM_PUBLISH_STATES.PUBLISHED,
      published_at: '2026-05-07T10:15:00.000Z',
      published_by: SEED_IDS.USER_ADMIN_GROWTHLAB,
      sort_order: 40,
      source_task_id: null,
      status: CLIENT_WORK_ITEM_STATUSES.PLANNED,
      summary: 'We are preparing a short SEO cleanup pass for the landing page after the current conversion updates.',
      target_date: '2026-05-16',
      title: 'Plan landing page SEO cleanup',
      updated_at: '2026-05-07T10:15:00.000Z',
    },
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-04-20T09:00:00.000Z',
      id: SEED_IDS.CLIENT_WORK_ARCHIVED_LAUNCH,
      last_reviewed_at: '2026-04-25T09:00:00.000Z',
      project_id: SEED_IDS.PROJECT_CAMPAIGN_SETUP,
      publish_state: CLIENT_WORK_ITEM_PUBLISH_STATES.ARCHIVED,
      published_at: '2026-04-22T09:00:00.000Z',
      published_by: SEED_IDS.USER_ADMIN_GROWTHLAB,
      sort_order: 100,
      source_task_id: null,
      status: CLIENT_WORK_ITEM_STATUSES.DELIVERED,
      summary: 'Initial campaign structure was delivered and moved into historical work.',
      target_date: '2026-04-25',
      title: 'Launch initial campaign structure',
      updated_at: '2026-04-25T09:00:00.000Z',
    },
  ],
  call_booking_metrics: [
    {
      answered_calls: 37,
      average_response_seconds: 92,
      booked_from_calls: 24,
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-08T09:00:00.000Z',
      data_source: 'Manual call tracking export',
      first_time_calls: 31,
      follow_up_needed_count: 5,
      form_leads: 14,
      id: SEED_IDS.CALL_BOOKING_EMERGENCY,
      insight: 'Emergency demand is being generated, but six missed calls are likely lost patient opportunities.',
      last_updated_at: '2026-05-08T09:00:00.000Z',
      location_id: SEED_IDS.CLINIC_LOCATION_GREEN_MAIN,
      missed_calls: 6,
      no_response_leads: 3,
      not_booked_reasons: [
        { count: 4, reason: 'No same-day slot available' },
        { count: 3, reason: 'Caller asked for unavailable pricing' },
      ],
      period_end: '2026-05-31',
      period_label: 'May 2026',
      period_start: '2026-05-01',
      service_line_id: SEED_IDS.CLINIC_SERVICE_EMERGENCY_DENTAL,
      summary: 'Emergency calls have strong booking intent and need tighter missed-call follow-up.',
      total_calls: 43,
      updated_at: '2026-05-08T09:00:00.000Z',
    },
    {
      answered_calls: 19,
      average_response_seconds: 138,
      booked_from_calls: 11,
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-08T09:00:00.000Z',
      data_source: 'Manual call tracking export',
      first_time_calls: 16,
      follow_up_needed_count: 4,
      form_leads: 9,
      id: SEED_IDS.CALL_BOOKING_IMPLANTS,
      insight: 'Implant consults convert well when answered, but response time is slower than the front-desk target.',
      last_updated_at: '2026-05-08T09:00:00.000Z',
      location_id: SEED_IDS.CLINIC_LOCATION_GREEN_MAIN,
      missed_calls: 3,
      no_response_leads: 2,
      not_booked_reasons: [
        { count: 3, reason: 'Needed financing details' },
        { count: 2, reason: 'Consult availability did not match caller schedule' },
      ],
      period_end: '2026-05-31',
      period_label: 'May 2026',
      period_start: '2026-05-01',
      service_line_id: SEED_IDS.CLINIC_SERVICE_IMPLANTS,
      summary: 'Implant call handling is acceptable but needs faster response and financing script clarity.',
      total_calls: 22,
      updated_at: '2026-05-08T09:00:00.000Z',
    },
  ],
  reputation_snapshots: [
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-08T09:00:00.000Z',
      data_source: 'Manual Google Business Profile + review export',
      gbp_updates: 4,
      google_rating: 4.7,
      id: SEED_IDS.REPUTATION_GREEN_MAIN,
      insight: 'Review volume is improving, but three unanswered reviews should be closed before scaling high-intent campaigns.',
      last_updated_at: '2026-05-08T09:00:00.000Z',
      local_visibility_note: 'GBP service categories are aligned for implants and emergency care; whitening offer copy still needs approval.',
      location_id: SEED_IDS.CLINIC_LOCATION_GREEN_MAIN,
      negative_reviews: 2,
      period_end: '2026-05-31',
      period_label: 'May 2026',
      period_start: '2026-05-01',
      provider_profile_completeness: 0.86,
      review_count: 286,
      review_request_sent: 142,
      review_response_drafts: 3,
      reviews_gained: 18,
      summary: 'Local trust is healthy, with review generation ahead of the monthly baseline.',
      unanswered_reviews: 3,
      updated_at: '2026-05-08T09:00:00.000Z',
    },
  ],
  clinic_profiles: [
    {
      capacity_notes: 'Implant consult capacity is strongest on Tuesday and Thursday. Emergency appointments need same-day slot protection.',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-01T09:00:00.000Z',
      id: SEED_IDS.CLINIC_PROFILE_GREEN,
      insurance_model: 'Mixed insurance and private-pay treatment plans.',
      primary_goal: 'Increase booked new patient appointments for high-value dental services without increasing missed-call leakage.',
      specialty: CLINIC_PROFILE_SPECIALTIES.DENTAL,
      updated_at: '2026-05-08T09:00:00.000Z',
    },
  ],
  clinic_locations: [
    {
      address: '124 Market Street',
      city: 'Austin',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-01T09:00:00.000Z',
      display_order: 10,
      id: SEED_IDS.CLINIC_LOCATION_GREEN_MAIN,
      is_active: true,
      name: 'Green Dental Main Clinic',
      updated_at: '2026-05-08T09:00:00.000Z',
    },
  ],
  clinic_service_lines: [
    {
      average_value: 4200,
      capacity_note: 'Two implant consult slots remain open per week; keep qualification strict before scaling.',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-01T09:00:00.000Z',
      display_order: 10,
      id: SEED_IDS.CLINIC_SERVICE_IMPLANTS,
      location_ids: [SEED_IDS.CLINIC_LOCATION_GREEN_MAIN],
      name: 'Dental Implants',
      primary_channel: 'google_ads',
      status: CLINIC_SERVICE_LINE_STATUSES.ACTIVE,
      target_monthly_bookings: 24,
      updated_at: '2026-05-08T09:00:00.000Z',
    },
    {
      average_value: 180,
      capacity_note: 'Reception needs same-day follow-up on missed emergency calls.',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-01T09:00:00.000Z',
      display_order: 20,
      id: SEED_IDS.CLINIC_SERVICE_EMERGENCY_DENTAL,
      location_ids: [SEED_IDS.CLINIC_LOCATION_GREEN_MAIN],
      name: 'Emergency Dental Appointments',
      primary_channel: 'google_ads',
      status: CLINIC_SERVICE_LINE_STATUSES.ACTIVE,
      target_monthly_bookings: 45,
      updated_at: '2026-05-08T09:00:00.000Z',
    },
    {
      average_value: 650,
      capacity_note: 'Offer wording requires approval before the next creative test.',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-01T09:00:00.000Z',
      display_order: 30,
      id: SEED_IDS.CLINIC_SERVICE_WHITENING,
      location_ids: [SEED_IDS.CLINIC_LOCATION_GREEN_MAIN],
      name: 'Teeth Whitening',
      primary_channel: 'meta_ads',
      status: CLINIC_SERVICE_LINE_STATUSES.PLANNED,
      target_monthly_bookings: 30,
      updated_at: '2026-05-08T09:00:00.000Z',
    },
  ],
  patient_acquisition_snapshots: [
    {
      attended_appointments: 12,
      booked_appointments: 14,
      calls: 18,
      channel: CLINIC_ACQUISITION_CHANNELS.GOOGLE_ADS,
      chats: 3,
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      clicks: 240,
      created_at: '2026-05-08T09:00:00.000Z',
      data_source: 'Manual Google Ads + call tracking export',
      forms: 9,
      id: SEED_IDS.CLINIC_ACQUISITION_IMPLANTS_GOOGLE,
      impressions: 12800,
      insight: 'Implant inquiries are efficient, but capacity should stay capped until consult availability improves.',
      landing_page_visits: 211,
      last_updated_at: '2026-05-08T09:00:00.000Z',
      location_id: SEED_IDS.CLINIC_LOCATION_GREEN_MAIN,
      period_end: '2026-05-31',
      period_label: 'May 2026',
      period_start: '2026-05-01',
      qualified_inquiries: 21,
      service_line_id: SEED_IDS.CLINIC_SERVICE_IMPLANTS,
      spend: 1860,
      summary: 'Google Ads is producing high-intent implant consult demand.',
      updated_at: '2026-05-08T09:00:00.000Z',
    },
    {
      attended_appointments: 22,
      booked_appointments: 27,
      calls: 41,
      channel: CLINIC_ACQUISITION_CHANNELS.GOOGLE_ADS,
      chats: 7,
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      clicks: 310,
      created_at: '2026-05-08T09:00:00.000Z',
      data_source: 'Manual Google Ads + call tracking export',
      forms: 14,
      id: SEED_IDS.CLINIC_ACQUISITION_EMERGENCY_GOOGLE,
      impressions: 15400,
      insight: 'Emergency demand is strong, but missed-call follow-up is the biggest leakage risk.',
      landing_page_visits: 286,
      last_updated_at: '2026-05-08T09:00:00.000Z',
      location_id: SEED_IDS.CLINIC_LOCATION_GREEN_MAIN,
      period_end: '2026-05-31',
      period_label: 'May 2026',
      period_start: '2026-05-01',
      qualified_inquiries: 34,
      service_line_id: SEED_IDS.CLINIC_SERVICE_EMERGENCY_DENTAL,
      spend: 2120,
      summary: 'Emergency appointment campaigns are driving the highest inquiry volume.',
      updated_at: '2026-05-08T09:00:00.000Z',
    },
    {
      attended_appointments: 8,
      booked_appointments: 10,
      calls: 7,
      channel: CLINIC_ACQUISITION_CHANNELS.META_ADS,
      chats: 5,
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      clicks: 420,
      created_at: '2026-05-08T09:00:00.000Z',
      data_source: 'Manual Meta Ads + CRM export',
      forms: 23,
      id: SEED_IDS.CLINIC_ACQUISITION_WHITENING_META,
      impressions: 28500,
      insight: 'Whitening interest is broad; offer language needs approval before scaling.',
      landing_page_visits: 338,
      last_updated_at: '2026-05-08T09:00:00.000Z',
      location_id: SEED_IDS.CLINIC_LOCATION_GREEN_MAIN,
      period_end: '2026-05-31',
      period_label: 'May 2026',
      period_start: '2026-05-01',
      qualified_inquiries: 18,
      service_line_id: SEED_IDS.CLINIC_SERVICE_WHITENING,
      spend: 980,
      summary: 'Meta Ads is useful for whitening demand but needs stronger qualification.',
      updated_at: '2026-05-08T09:00:00.000Z',
    },
  ],
  client_file_links: [
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-08T09:25:00.000Z',
      description: 'Shared folder for the latest approved logos, colors, photography, and clinic brand references.',
      display_order: 10,
      file_name: '',
      id: SEED_IDS.FILE_BRAND_ASSETS,
      mime_type: '',
      project_id: null,
      related_report_id: null,
      related_work_item_id: null,
      status: CLIENT_FILE_LINK_STATUSES.ACTIVE,
      title: 'Brand assets folder',
      type: CLIENT_FILE_LINK_TYPES.BRAND_ASSET,
      updated_at: '2026-05-08T09:25:00.000Z',
      uploaded_by_name: 'GrowthLab',
      url: 'https://drive.google.com/brand-assets-green-dental',
      visibility: VISIBILITY.CLIENT_VISIBLE,
    },
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-08T09:30:00.000Z',
      description: 'Creative review folder for the second Meta Ads batch.',
      display_order: 20,
      file_name: '',
      id: SEED_IDS.FILE_CREATIVE_BATCH,
      mime_type: '',
      project_id: SEED_IDS.PROJECT_CAMPAIGN_SETUP,
      related_report_id: null,
      related_work_item_id: SEED_IDS.CLIENT_WORK_REVIEW_CREATIVES,
      status: CLIENT_FILE_LINK_STATUSES.ACTIVE,
      title: 'Meta Ads creative batch #2',
      type: CLIENT_FILE_LINK_TYPES.DELIVERABLE,
      updated_at: '2026-05-08T09:30:00.000Z',
      uploaded_by_name: 'GrowthLab',
      url: 'https://drive.google.com/creative-batch-green-dental',
      visibility: VISIBILITY.CLIENT_VISIBLE,
    },
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-08T09:35:00.000Z',
      description: 'Live shared workspace used for campaign resources, approved links, and handoff notes.',
      display_order: 30,
      file_name: '',
      id: SEED_IDS.FILE_SHARED_DRIVE,
      mime_type: '',
      project_id: SEED_IDS.PROJECT_REPORTING,
      related_report_id: null,
      related_work_item_id: SEED_IDS.CLIENT_WORK_GA4_CONVERSION,
      status: CLIENT_FILE_LINK_STATUSES.ACTIVE,
      title: 'Shared campaign workspace',
      type: CLIENT_FILE_LINK_TYPES.SHARED_LINK,
      updated_at: '2026-05-08T09:35:00.000Z',
      uploaded_by_name: 'GrowthLab',
      url: 'https://drive.google.com/shared-campaign-green-dental',
      visibility: VISIBILITY.CLIENT_VISIBLE,
    },
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-08T10:00:00.000Z',
      description: 'Published PDF version of the April monthly performance report.',
      display_order: 40,
      file_name: 'green-dental-april-2026-report.pdf',
      id: SEED_IDS.FILE_REPORT_PDF,
      mime_type: 'application/pdf',
      project_id: SEED_IDS.PROJECT_REPORTING,
      related_report_id: SEED_IDS.REPORT_APRIL_2026,
      related_work_item_id: null,
      status: CLIENT_FILE_LINK_STATUSES.ACTIVE,
      title: 'April 2026 report PDF',
      type: CLIENT_FILE_LINK_TYPES.REPORT,
      updated_at: '2026-05-08T10:00:00.000Z',
      uploaded_by_name: 'GrowthLab',
      url: 'https://example.com/green-dental-april-report.pdf',
      visibility: VISIBILITY.CLIENT_VISIBLE,
    },
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-04-25T10:00:00.000Z',
      description: 'Historical handoff folder for the initial campaign launch files.',
      display_order: 50,
      file_name: '',
      id: SEED_IDS.FILE_INITIAL_CAMPAIGN_ARCHIVE,
      mime_type: '',
      project_id: SEED_IDS.PROJECT_CAMPAIGN_SETUP,
      related_report_id: null,
      related_work_item_id: SEED_IDS.CLIENT_WORK_ARCHIVED_LAUNCH,
      status: CLIENT_FILE_LINK_STATUSES.ARCHIVED,
      title: 'Initial campaign launch archive',
      type: CLIENT_FILE_LINK_TYPES.DELIVERABLE,
      updated_at: '2026-04-25T10:00:00.000Z',
      uploaded_by_name: 'GrowthLab',
      url: 'https://drive.google.com/initial-campaign-launch-archive',
      visibility: VISIBILITY.CLIENT_VISIBLE,
    },
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-08T08:30:00.000Z',
      description: 'Internal tracking notes are never exposed in the client portal.',
      display_order: 999,
      file_name: '',
      id: SEED_IDS.FILE_INTERNAL_TRACKING,
      mime_type: '',
      project_id: SEED_IDS.PROJECT_REPORTING,
      related_report_id: null,
      related_work_item_id: SEED_IDS.CLIENT_WORK_INTERNAL_DRAFT,
      status: CLIENT_FILE_LINK_STATUSES.ACTIVE,
      title: 'Internal tracking debug notes',
      type: CLIENT_FILE_LINK_TYPES.SHARED_LINK,
      updated_at: '2026-05-08T08:30:00.000Z',
      uploaded_by_name: 'GrowthLab',
      url: 'https://docs.example.com/internal-tracking-debug',
      visibility: VISIBILITY.INTERNAL,
    },
  ],
  clients: [
    {
      agency_id: SEED_IDS.AGENCY_GROWTHLAB,
      created_at: '2026-05-01T09:00:00.000Z',
      current_focus: [
        'Meta Ads campaign optimization',
        'Landing page conversion improvements',
        'Follow-up automation setup',
      ],
      id: SEED_IDS.CLIENT_GREEN_DENTAL,
      logo_url: '',
      name: 'Green Dental Clinic',
      portal_slug: 'green-dental-clinic',
      primary_contact_email: 'sarah@greendental.example',
      primary_contact_name: 'Sarah Johnson',
      status: CLIENT_STATUSES.ON_TRACK,
      type: CLIENT_TYPES.CLINIC,
      updated_at: '2026-05-08T09:00:00.000Z',
    },
    {
      agency_id: SEED_IDS.AGENCY_GROWTHLAB,
      created_at: '2026-05-02T09:00:00.000Z',
      current_focus: [
        'Local SEO cleanup',
        'New patient offer validation',
      ],
      id: SEED_IDS.CLIENT_NORTHSTAR_DENTAL,
      logo_url: '',
      name: 'Northstar Dental Studio',
      portal_slug: 'northstar-dental-studio',
      primary_contact_email: 'ops@northstar.example',
      primary_contact_name: 'Olivia Chen',
      status: CLIENT_STATUSES.WAITING_CLIENT,
      type: CLIENT_TYPES.CLINIC,
      updated_at: '2026-05-08T09:00:00.000Z',
    },
  ],
  dashboard_links: [
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-01T09:00:00.000Z',
      description: 'Executive marketing performance dashboard covering spend, lead flow, CPL, and conversion trends.',
      display_order: 10,
      embed_url: 'https://lookerstudio.google.com/embed/reporting/demo-green-dental',
      fallback_message: 'Marketing dashboard is being prepared.',
      id: SEED_IDS.DASHBOARD_GREEN_APRIL,
      last_checked_at: '2026-05-08T09:00:00.000Z',
      name: 'Marketing Performance Dashboard',
      provider: DASHBOARD_PROVIDERS.LOOKER_STUDIO,
      public_url: 'https://lookerstudio.google.com/reporting/demo-green-dental',
      show_on_overview: true,
      status: DASHBOARD_LINK_STATUSES.ACTIVE,
      updated_at: '2026-05-08T09:00:00.000Z',
      visibility: VISIBILITY.CLIENT_VISIBLE,
    },
  ],
  needed_from_client: [
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-06T10:00:00.000Z',
      description: 'Confirm the final discount and treatment package wording before campaign scaling.',
      due_date: '2026-05-10',
      id: SEED_IDS.NEEDED_OFFER_DETAILS,
      internal_notes: 'Confirm before increasing campaign budget.',
      owner_name: 'Sarah Johnson',
      priority: NEEDED_ACTION_PRIORITIES.HIGH,
      related_link: '',
      status: NEEDED_ACTION_STATUSES.PENDING,
      title: 'Confirm final offer details',
      type: NEEDED_ACTION_TYPES.DECISION,
      updated_at: '2026-05-06T10:00:00.000Z',
    },
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-05T10:00:00.000Z',
      description: 'Approve or request edits on the second creative batch.',
      due_date: '2026-05-09',
      id: SEED_IDS.NEEDED_CREATIVE_APPROVAL,
      internal_notes: 'Creative batch blocks the next ad test.',
      owner_name: 'Sarah Johnson',
      priority: NEEDED_ACTION_PRIORITIES.MEDIUM,
      related_link: 'https://drive.google.com/example',
      related_task_id: SEED_IDS.TASK_REVIEW_CREATIVES,
      related_work_item_id: SEED_IDS.CLIENT_WORK_REVIEW_CREATIVES,
      status: NEEDED_ACTION_STATUSES.PENDING,
      title: 'Approve creative batch #2',
      type: NEEDED_ACTION_TYPES.APPROVAL,
      updated_at: '2026-05-05T10:00:00.000Z',
    },
  ],
  performance_dashboard_periods: [
    {
      account_manager: 'Sarah Johnson',
      agency_contact: 'sarah@growthlab.example',
      attribution_note: 'Manual report compiled from CRM, ad platform exports, and Looker Studio. Revenue uses last-click attribution where available.',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      content: {
        appendix_tables: [
          {
            columns: ['Campaign', 'Spend', 'Qualified Leads', 'CPL', 'Status'],
            display_order: 10,
            id: 'table-green-april-campaigns',
            rows: [
              ['Dental Implants Search', '$3,200', '42', '$76.19', 'Scaling'],
              ['Emergency Dentist Meta', '$1,850', '21', '$88.10', 'Review quality'],
              ['Teeth Whitening Retargeting', '$900', '16', '$56.25', 'Stable'],
            ],
            title: 'Top Campaigns',
          },
        ],
        campaign_execution: createGreenDentalReactivationCampaignExecution(),
        channel_breakdown: [
          {
            channel: PERFORMANCE_CHANNELS.GOOGLE_ADS,
            conversion_rate: 0.118,
            cpl: 76.19,
            display_order: 10,
            id: 'channel-google-ads-april',
            leads: 68,
            qualified_leads: 42,
            revenue: 39200,
            roas: 5.4,
            spend: 3200,
            summary: 'Search campaigns produced the highest-quality appointment requests.',
          },
          {
            channel: PERFORMANCE_CHANNELS.META_ADS,
            conversion_rate: 0.074,
            cpl: 88.1,
            display_order: 20,
            id: 'channel-meta-ads-april',
            leads: 44,
            qualified_leads: 21,
            revenue: 18600,
            roas: 3.1,
            spend: 1850,
            summary: 'Meta volume improved, but qualification needs tightening before scaling.',
          },
          {
            channel: PERFORMANCE_CHANNELS.SEO,
            conversion_rate: 0.092,
            cpl: 0,
            display_order: 30,
            id: 'channel-seo-april',
            leads: 29,
            qualified_leads: 18,
            revenue: 15400,
            roas: null,
            spend: 0,
            summary: 'Organic appointment requests increased after local service page updates.',
          },
        ],
        executive_summary: {
          main_issue: 'Meta lead quality is improving but still below the standard needed for budget scaling.',
          main_win: 'Qualified leads increased while blended CPL decreased.',
          narrative: 'April performance was positive. Marketing generated more qualified appointment opportunities, search campaigns produced the most reliable lead quality, and organic traffic started contributing more booked consultations.',
          next_focus: 'Scale search cautiously, tighten Meta qualification rules, and improve landing page proof around implant consultations.',
        },
        funnel: {
          booked_calls: 48,
          clicks: 2140,
          impressions: 84200,
          leads: 141,
          qualified_leads: 81,
          revenue: 73200,
          sales: 19,
          spend: 5950,
          visitors: 1780,
        },
        goals: [
          {
            actual: 81,
            display_order: 10,
            id: 'goal-qualified-leads-april',
            metric: 'qualified_leads',
            name: 'Qualified Leads',
            note: 'Target exceeded mainly through search and organic lead quality.',
            status: PERFORMANCE_GOAL_STATUSES.AHEAD,
            target: 72,
            target_date: '2026-04-30',
          },
          {
            actual: 73_200,
            display_order: 20,
            id: 'goal-attributed-revenue-april',
            metric: 'revenue_attributed',
            name: 'Attributed Revenue',
            note: 'Revenue is directional because offline close tracking is manually reconciled.',
            status: PERFORMANCE_GOAL_STATUSES.ON_TRACK,
            target: 70_000,
            target_date: '2026-04-30',
          },
        ],
        hero_metric: {
          benchmark: 'Goal: 72',
          definition: 'Leads approved as real appointment opportunities after front desk review.',
          delta_abs: '+13',
          delta_pct: 19.1,
          goal: 72,
          goal_pct: 112.5,
          label: 'Qualified Leads',
          source: 'CRM export + manual review',
          status: PERFORMANCE_METRIC_STATUSES.AHEAD,
          unit: '',
          value: 81,
        },
        insights: [
          {
            body: 'Search lead quality improved after negative keyword cleanup and tighter appointment-intent ad copy.',
            chart_ref: 'trend-qualified-leads-april',
            display_order: 10,
            id: 'insight-search-quality-april',
            severity: PERFORMANCE_INSIGHT_SEVERITIES.POSITIVE,
            title: 'Search quality improved',
          },
          {
            body: 'Meta campaigns produced cheaper form submissions, but the front desk marked more of them as low-intent. We should tighten the offer and qualifying questions before scaling.',
            chart_ref: 'channel-meta-ads-april',
            display_order: 20,
            id: 'insight-meta-quality-april',
            severity: PERFORMANCE_INSIGHT_SEVERITIES.WARNING,
            title: 'Meta needs qualification work',
          },
        ],
        kpi_cards: [
          {
            benchmark: 'Goal: 72',
            definition: 'Leads approved as real appointment opportunities after review.',
            delta_abs: '+13',
            delta_pct: 19.1,
            display_order: 10,
            goal: 72,
            id: 'kpi-qualified-leads-april',
            name: 'Qualified Leads',
            prior_value: 68,
            source: 'CRM export',
            sparkline: [58, 61, 64, 68, 74, 81],
            status: PERFORMANCE_METRIC_STATUSES.AHEAD,
            unit: '',
            value: 81,
          },
          {
            benchmark: 'Target: <$80',
            definition: 'Total spend divided by qualified leads.',
            delta_abs: '-$8.40',
            delta_pct: -10.2,
            display_order: 20,
            goal: 80,
            id: 'kpi-blended-cpl-april',
            name: 'Blended CPL',
            prior_value: 81.86,
            source: 'Ad exports + CRM export',
            sparkline: [86, 84, 82, 80, 76, 73.46],
            status: PERFORMANCE_METRIC_STATUSES.AHEAD,
            unit: '$',
            value: 73.46,
          },
          {
            benchmark: 'Goal: $70,000',
            definition: 'Revenue connected to marketing leads where source tracking is available.',
            delta_abs: '+$9,800',
            delta_pct: 15.5,
            display_order: 30,
            goal: 70000,
            id: 'kpi-revenue-april',
            name: 'Attributed Revenue',
            prior_value: 63400,
            source: 'CRM manual reconciliation',
            sparkline: [52000, 56600, 59800, 63400, 68200, 73200],
            status: PERFORMANCE_METRIC_STATUSES.ON_TRACK,
            unit: '$',
            value: 73200,
          },
          {
            benchmark: 'Target: 9%',
            definition: 'Website visitors who became leads.',
            delta_abs: '+1.1pp',
            delta_pct: 15.1,
            display_order: 40,
            goal: 0.09,
            id: 'kpi-conversion-rate-april',
            name: 'Lead Conversion Rate',
            prior_value: 0.079,
            source: 'GA4 + form tracking',
            sparkline: [0.068, 0.071, 0.075, 0.079, 0.083, 0.09],
            status: PERFORMANCE_METRIC_STATUSES.ON_TRACK,
            unit: '%',
            value: 0.09,
          },
        ],
        next_steps: [
          {
            description: 'Move budget toward high-intent search terms while keeping CPL under target.',
            display_order: 10,
            due_date: '2026-05-10',
            id: 'next-step-search-scale-april',
            owner: 'GrowthLab',
            priority: PERFORMANCE_NEXT_STEP_PRIORITIES.HIGH,
            title: 'Scale winning search campaigns cautiously',
          },
          {
            description: 'Add stronger qualification questions before asking the client to increase Meta budget.',
            display_order: 20,
            due_date: '2026-05-12',
            id: 'next-step-meta-qualification-april',
            owner: 'GrowthLab',
            priority: PERFORMANCE_NEXT_STEP_PRIORITIES.MEDIUM,
            title: 'Improve Meta lead qualification',
          },
        ],
        service_sections: [
          {
            display_order: 10,
            id: 'service-paid-ads-april',
            insights: [
              'Google Ads drove the most reliable appointment requests.',
              'Meta should stay in test mode until quality improves.',
            ],
            metrics: {
              cpl: 79.84,
              qualified_leads: 63,
              roas: 4.45,
              spend: 5050,
            },
            next_actions: [
              'Increase exact-match search budget gradually.',
              'Refine Meta form questions.',
            ],
            service_type: PERFORMANCE_SERVICE_TYPES.PAID_ADS,
            summary: 'Paid acquisition produced the majority of qualified leads while CPL moved below target.',
          },
        ],
        trends: [
          {
            annotations: [
              {
                date: '2026-04-15',
                label: 'Negative keyword cleanup',
              },
              {
                date: '2026-04-22',
                label: 'Landing page proof update',
              },
            ],
            comparison_series: [
              { date: '2026-03-01', value: 54 },
              { date: '2026-03-08', value: 57 },
              { date: '2026-03-15', value: 60 },
              { date: '2026-03-22', value: 64 },
              { date: '2026-03-29', value: 68 },
            ],
            display_order: 10,
            goal_value: 72,
            granularity: PERFORMANCE_TREND_GRANULARITIES.WEEKLY,
            id: 'trend-qualified-leads-april',
            metric: 'qualified_leads',
            series: [
              { date: '2026-04-01', value: 61 },
              { date: '2026-04-08', value: 65 },
              { date: '2026-04-15', value: 71 },
              { date: '2026-04-22', value: 77 },
              { date: '2026-04-30', value: 81 },
            ],
          },
        ],
      },
      created_at: '2026-05-05T09:00:00.000Z',
      created_by: SEED_IDS.USER_ADMIN_GROWTHLAB,
      data_confidence: PERFORMANCE_DATA_CONFIDENCE.MEDIUM,
      data_mode: PERFORMANCE_DATA_MODES.MANUAL,
      id: SEED_IDS.PERFORMANCE_GREEN_APRIL,
      last_updated_at: '2026-05-05T09:00:00.000Z',
      period_end: '2026-04-30',
      period_start: '2026-04-01',
      published_at: '2026-05-05T10:00:00.000Z',
      source_summary: 'Manual dashboard compiled from CRM, ad platform exports, GA4, and Looker Studio.',
      status: PERFORMANCE_DASHBOARD_STATUSES.PUBLISHED,
      title: 'April 2026 Performance Dashboard',
      updated_at: '2026-05-05T10:00:00.000Z',
      updated_by: SEED_IDS.USER_ADMIN_GROWTHLAB,
    },
    {
      account_manager: 'Sarah Johnson',
      agency_contact: 'sarah@growthlab.example',
      attribution_note: 'Archived March dashboard.',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      content: {
        executive_summary: {
          main_issue: 'Landing page conversion was below target.',
          main_win: 'Search campaigns established baseline lead flow.',
          narrative: 'March established the first reliable lead generation baseline.',
          next_focus: 'Improve conversion rate and lead qualification.',
        },
        hero_metric: {
          label: 'Qualified Leads',
          source: 'Manual',
          status: PERFORMANCE_METRIC_STATUSES.ON_TRACK,
          value: 68,
        },
        insights: [
          {
            body: 'Search produced consistent lead volume, but landing page conversion was still early.',
            id: 'insight-march-baseline',
            title: 'Baseline established',
          },
        ],
        kpi_cards: [
          {
            id: 'kpi-march-qualified-leads',
            name: 'Qualified Leads',
            source: 'CRM export',
            value: 68,
          },
        ],
        next_steps: [
          {
            id: 'next-step-march-lp',
            title: 'Improve landing page proof',
          },
        ],
      },
      created_at: '2026-04-04T09:00:00.000Z',
      created_by: SEED_IDS.USER_ADMIN_GROWTHLAB,
      data_confidence: PERFORMANCE_DATA_CONFIDENCE.MEDIUM,
      data_mode: PERFORMANCE_DATA_MODES.MANUAL,
      id: SEED_IDS.PERFORMANCE_GREEN_ARCHIVED_MARCH,
      last_updated_at: '2026-04-04T09:00:00.000Z',
      period_end: '2026-03-31',
      period_start: '2026-03-01',
      published_at: '2026-04-04T10:00:00.000Z',
      source_summary: 'Manual dashboard compiled from campaign exports.',
      status: PERFORMANCE_DASHBOARD_STATUSES.ARCHIVED,
      title: 'March 2026 Performance Dashboard',
      updated_at: '2026-04-04T10:00:00.000Z',
      updated_by: SEED_IDS.USER_ADMIN_GROWTHLAB,
    },
    {
      account_manager: 'Sarah Johnson',
      agency_contact: 'sarah@growthlab.example',
      attribution_note: '',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      content: {
        executive_summary: {
          main_issue: '',
          main_win: '',
          narrative: '',
          next_focus: '',
        },
        hero_metric: {
          label: '',
          value: '',
        },
        insights: [],
        kpi_cards: [],
        next_steps: [],
      },
      created_at: '2026-05-12T09:00:00.000Z',
      created_by: SEED_IDS.USER_ADMIN_GROWTHLAB,
      data_confidence: PERFORMANCE_DATA_CONFIDENCE.ESTIMATED,
      data_mode: PERFORMANCE_DATA_MODES.JSON_IMPORT,
      id: SEED_IDS.PERFORMANCE_GREEN_DRAFT_MAY,
      last_updated_at: '',
      period_end: '2026-05-31',
      period_start: '2026-05-01',
      published_at: null,
      source_summary: '',
      status: PERFORMANCE_DASHBOARD_STATUSES.DRAFT,
      title: 'May 2026 Performance Draft',
      updated_at: '2026-05-12T09:00:00.000Z',
      updated_by: SEED_IDS.USER_ADMIN_GROWTHLAB,
    },
    {
      account_manager: 'Sarah Johnson',
      agency_contact: 'sarah@growthlab.example',
      attribution_note: 'Northstar demo performance period.',
      client_id: SEED_IDS.CLIENT_NORTHSTAR_DENTAL,
      content: {
        executive_summary: {
          main_issue: 'Waiting on offer approval.',
          main_win: 'Local SEO cleanup completed.',
          narrative: 'Northstar has early setup data but is not ready for client-facing performance review.',
          next_focus: 'Approve offer and launch paid acquisition.',
        },
        hero_metric: {
          label: 'Booked Calls',
          source: 'Manual',
          value: 12,
        },
        insights: [
          {
            body: 'Local SEO cleanup is complete, but paid campaigns are waiting on approval.',
            id: 'insight-northstar-setup',
            title: 'Setup waiting on client',
          },
        ],
        kpi_cards: [
          {
            id: 'kpi-northstar-booked-calls',
            name: 'Booked Calls',
            value: 12,
          },
        ],
        next_steps: [
          {
            id: 'next-step-northstar-offer',
            title: 'Approve new patient offer',
          },
        ],
      },
      created_at: '2026-05-05T09:00:00.000Z',
      created_by: SEED_IDS.USER_ADMIN_GROWTHLAB,
      data_confidence: PERFORMANCE_DATA_CONFIDENCE.LOW,
      data_mode: PERFORMANCE_DATA_MODES.MANUAL,
      id: SEED_IDS.PERFORMANCE_NORTHSTAR_APRIL,
      last_updated_at: '2026-05-05T09:00:00.000Z',
      period_end: '2026-04-30',
      period_start: '2026-04-01',
      published_at: '2026-05-05T10:00:00.000Z',
      source_summary: 'Manual setup period.',
      status: PERFORMANCE_DASHBOARD_STATUSES.PUBLISHED,
      title: 'April 2026 Northstar Performance Dashboard',
      updated_at: '2026-05-05T10:00:00.000Z',
      updated_by: SEED_IDS.USER_ADMIN_GROWTHLAB,
    },
  ],
  profiles: [
    {
      agency_id: SEED_IDS.AGENCY_GROWTHLAB,
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-01T09:00:00.000Z',
      email: 'client@greendental.example',
      id: SEED_IDS.PROFILE_CLIENT_GREEN,
      name: 'Green Dental Client',
      role: USER_ROLES.CLIENT_USER,
      updated_at: '2026-05-08T09:00:00.000Z',
      user_id: SEED_IDS.USER_CLIENT_GREEN,
    },
    {
      agency_id: SEED_IDS.AGENCY_GROWTHLAB,
      client_id: null,
      created_at: '2026-05-01T09:00:00.000Z',
      email: 'admin@growthlab.example',
      id: SEED_IDS.PROFILE_ADMIN_GROWTHLAB,
      name: 'GrowthLab Admin',
      role: USER_ROLES.AGENCY_ADMIN,
      updated_at: '2026-05-08T09:00:00.000Z',
      user_id: SEED_IDS.USER_ADMIN_GROWTHLAB,
    },
    {
      agency_id: SEED_IDS.AGENCY_GROWTHLAB,
      client_id: null,
      client_ids: [SEED_IDS.CLIENT_GREEN_DENTAL],
      created_at: '2026-05-01T09:00:00.000Z',
      email: 'mia@growthlab.example',
      id: SEED_IDS.PROFILE_TEAM_MIA,
      name: 'Mia Carter',
      role: USER_ROLES.AGENCY_TEAM,
      updated_at: '2026-05-08T09:00:00.000Z',
      user_id: SEED_IDS.USER_TEAM_MIA,
    },
  ],
  projects: [
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-01T09:00:00.000Z',
      description: 'Initial campaign structure, tracking, landing page, and reporting setup.',
      end_date: '2026-05-31',
      id: SEED_IDS.PROJECT_CAMPAIGN_SETUP,
      name: 'Campaign Setup',
      progress_percent: 80,
      start_date: '2026-05-01',
      status: 'in_progress',
      updated_at: '2026-05-08T09:00:00.000Z',
    },
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-01T09:00:00.000Z',
      description: 'Improve landing page conversion and follow-up clarity.',
      end_date: '2026-05-31',
      id: SEED_IDS.PROJECT_LANDING_PAGE,
      name: 'Landing Page Updates',
      progress_percent: 60,
      start_date: '2026-05-01',
      status: 'in_progress',
      updated_at: '2026-05-08T09:00:00.000Z',
    },
    {
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-01T09:00:00.000Z',
      description: 'Dashboard embed and monthly reporting workflow.',
      end_date: '2026-05-31',
      id: SEED_IDS.PROJECT_REPORTING,
      name: 'Reporting Setup',
      progress_percent: 40,
      start_date: '2026-05-01',
      status: 'in_progress',
      updated_at: '2026-05-08T09:00:00.000Z',
    },
  ],
  reports: [
    {
      client_decisions_needed: 'Approve the next creative batch and confirm final offer wording.',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-01T09:00:00.000Z',
      dashboard_url: 'https://lookerstudio.google.com/reporting/demo-green-dental',
      id: SEED_IDS.REPORT_APRIL_2026,
      next_actions: 'Scale winning ad angle, improve landing page proof section, and monitor CPL stability.',
      pdf_url: '',
      period_end: '2026-04-30',
      period_start: '2026-04-01',
      problems: 'Conversion data is still early and needs another week before larger budget decisions.',
      published_at: '2026-05-04T09:00:00.000Z',
      status: REPORT_STATUSES.PUBLISHED,
      summary: 'April launched the first paid acquisition structure and produced stable early lead quality. The next priority is scaling only after more conversion data is available.',
      title: 'April 2026 Monthly Summary',
      updated_at: '2026-05-04T09:00:00.000Z',
      wins: 'First campaign structure launched, tracking baseline connected, and three ad angles entered testing.',
    },
  ],
  tasks: [
    {
      assignee_name: 'Mia Carter',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      client_visible: true,
      created_at: '2026-05-01T09:00:00.000Z',
      description: 'Client approval is needed before the next paid campaign push.',
      due_date: '2026-05-09',
      id: SEED_IDS.TASK_REVIEW_CREATIVES,
      internal_note: 'Client should approve creative batch before the next paid push.',
      project_id: SEED_IDS.PROJECT_CAMPAIGN_SETUP,
      sort_order: 10,
      status: TASK_STATUSES.WAITING_CLIENT,
      title: 'Review new ad creatives',
      updated_at: '2026-05-08T09:00:00.000Z',
      visibility: VISIBILITY.CLIENT_VISIBLE,
    },
    {
      assignee_name: 'Leo Brooks',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      client_visible: true,
      created_at: '2026-05-01T09:00:00.000Z',
      description: 'Connect primary GA4 conversion event to campaign reporting.',
      due_date: '2026-05-11',
      id: SEED_IDS.TASK_GA4_CONVERSION,
      internal_note: '',
      project_id: SEED_IDS.PROJECT_REPORTING,
      sort_order: 20,
      status: TASK_STATUSES.IN_PROGRESS,
      title: 'Connect GA4 conversion event',
      updated_at: '2026-05-08T09:00:00.000Z',
      visibility: VISIBILITY.CLIENT_VISIBLE,
    },
    {
      assignee_name: 'Nora Lane',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      client_visible: true,
      created_at: '2026-05-01T09:00:00.000Z',
      description: 'Prepare concise client-facing summary for April performance.',
      due_date: '2026-05-12',
      id: SEED_IDS.TASK_MONTHLY_REPORT,
      internal_note: '',
      project_id: SEED_IDS.PROJECT_REPORTING,
      sort_order: 30,
      status: TASK_STATUSES.IN_PROGRESS,
      title: 'Prepare monthly report',
      updated_at: '2026-05-08T09:00:00.000Z',
      visibility: VISIBILITY.CLIENT_VISIBLE,
    },
    {
      assignee_name: 'Internal Team',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      client_visible: false,
      created_at: '2026-05-01T09:00:00.000Z',
      description: 'Internal implementation note; must never render to client users.',
      due_date: '2026-05-09',
      id: SEED_IDS.TASK_INTERNAL_DEBUGGING,
      internal_note: 'Mismatch between form-submit event and CRM lead count. Keep this internal.',
      project_id: SEED_IDS.PROJECT_REPORTING,
      sort_order: 99,
      status: TASK_STATUSES.BLOCKED,
      title: 'Debug internal tracking mismatch',
      updated_at: '2026-05-08T09:00:00.000Z',
      visibility: VISIBILITY.INTERNAL,
    },
  ],
  updates: [
    {
      body: 'This week we launched the first campaign structure, connected basic tracking, and started testing 3 ad angles. Early traffic quality looks stable, but we still need more conversion data before larger budget decisions.',
      client_action_needed: 'Approve the second creative batch so the next test can launch on schedule.',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-08T09:00:00.000Z',
      created_by: SEED_IDS.PROFILE_ADMIN_GROWTHLAB,
      id: SEED_IDS.UPDATE_WEEKLY_MAY_8,
      published_at: '2026-05-08T09:00:00.000Z',
      project_id: SEED_IDS.PROJECT_CAMPAIGN_SETUP,
      related_file_link_id: SEED_IDS.FILE_CREATIVE_BATCH,
      related_report_id: null,
      title: 'Weekly progress update',
      type: CLIENT_UPDATE_TYPES.WEEKLY_UPDATE,
      updated_at: '2026-05-08T09:00:00.000Z',
      visibility: VISIBILITY.CLIENT_VISIBLE,
      what_changed: 'The first campaign structure is live, basic tracking is connected, and 3 ad angles are now being tested.',
      what_next: 'Collect more conversion data before increasing budget.',
    },
    {
      body: 'The second creative batch is now staged for the next Meta Ads test.',
      client_action_needed: 'Review the creative folder and approve or request changes.',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-09T10:00:00.000Z',
      created_by: SEED_IDS.PROFILE_ADMIN_GROWTHLAB,
      id: SEED_IDS.UPDATE_CREATIVE_LAUNCH,
      published_at: '2026-05-09T10:00:00.000Z',
      project_id: SEED_IDS.PROJECT_CAMPAIGN_SETUP,
      related_file_link_id: SEED_IDS.FILE_CREATIVE_BATCH,
      related_report_id: null,
      title: 'Creative batch prepared for launch',
      type: CLIENT_UPDATE_TYPES.LAUNCH_UPDATE,
      updated_at: '2026-05-09T10:00:00.000Z',
      visibility: VISIBILITY.CLIENT_VISIBLE,
      what_changed: 'New ad variations were prepared and linked to the campaign setup project.',
      what_next: 'Launch the next creative test after client approval.',
    },
    {
      body: 'The April monthly report is now published with a summary of results, wins, issues, and next actions.',
      client_action_needed: '',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-10T10:00:00.000Z',
      created_by: SEED_IDS.PROFILE_ADMIN_GROWTHLAB,
      id: SEED_IDS.UPDATE_REPORT_PUBLISHED,
      published_at: '2026-05-10T10:00:00.000Z',
      project_id: SEED_IDS.PROJECT_REPORTING,
      related_file_link_id: SEED_IDS.FILE_REPORT_PDF,
      related_report_id: SEED_IDS.REPORT_APRIL_2026,
      title: 'April report published',
      type: CLIENT_UPDATE_TYPES.REPORT_PUBLISHED,
      updated_at: '2026-05-10T10:00:00.000Z',
      visibility: VISIBILITY.CLIENT_VISIBLE,
      what_changed: 'The April performance report and PDF are available in the portal.',
      what_next: 'Review the report before the next account call.',
    },
    {
      body: 'Internal tracking mismatch is under investigation.',
      client_id: SEED_IDS.CLIENT_GREEN_DENTAL,
      created_at: '2026-05-08T08:00:00.000Z',
      created_by: SEED_IDS.PROFILE_ADMIN_GROWTHLAB,
      id: SEED_IDS.UPDATE_INTERNAL_TRACKING,
      published_at: '2026-05-08T08:00:00.000Z',
      project_id: SEED_IDS.PROJECT_REPORTING,
      title: 'Internal tracking note',
      type: CLIENT_UPDATE_TYPES.ISSUE_UPDATE,
      updated_at: '2026-05-08T08:00:00.000Z',
      visibility: VISIBILITY.INTERNAL,
    },
  ],
})
