/* eslint-disable react-refresh/only-export-components */
import { lazy, Suspense } from 'react'
import { CLIENT_TYPES } from '../../entities/client'
import { CLINIC_REPORTING_CAPABILITIES } from '../../entities/profile'
import { ACCESS_AUDIENCES } from '../../domain/policies/accessAudience'
import { AcceptInvitePage } from '../../pages/auth/accept-invite/AcceptInvitePage'
import { LoginPage } from '../../pages/auth/login/LoginPage'
import { AdminClientsPageHeader } from '../../pages/admin/clients/AdminClientsPageHeader'
import { AdminDashboardLinksPageHeader } from '../../pages/admin/dashboard-links/AdminDashboardLinksPageHeader'
import { AdminPerformanceDashboardEditorPageHeader } from '../../pages/admin/performance-dashboard-editor/AdminPerformanceDashboardEditorPageHeader'
import { AdminPerformanceDashboardsPageHeader } from '../../pages/admin/performance-dashboards/AdminPerformanceDashboardsPageHeader'
import { AdminReportsPageHeader } from '../../pages/admin/reports/AdminReportsPageHeader'
import { ClientActionNeededPageHeader } from '../../pages/client/action-needed/ClientActionNeededPageHeader'
import { ClientCallsBookingsPageHeader } from '../../pages/client/calls-bookings/ClientCallsBookingsPageHeader'
import {
  ClientComplianceApprovalsPageHeader,
} from '../../pages/client/compliance-approvals/ClientComplianceApprovalsPageHeader'
import { ClientDashboardPageHeader } from '../../pages/client/dashboard/ClientDashboardPageHeader'
import { ClientFilesLinksPageHeader } from '../../pages/client/files-links/ClientFilesLinksPageHeader'
import { ClientOverviewPageHeader } from '../../pages/client/overview/ClientOverviewPageHeader'
import {
  ClientPatientAcquisitionPageHeader,
} from '../../pages/client/patient-acquisition/ClientPatientAcquisitionPageHeader'
import { ClientPerformancePageHeader } from '../../pages/client/performance/ClientPerformancePageHeader'
import { ClientProjectsPageHeader } from '../../pages/client/projects/ClientProjectsPageHeader'
import { ClientReportsDashboardsPageHeader } from '../../pages/client/reports-dashboards/ClientReportsDashboardsPageHeader'
import { ClientReportsPageHeader } from '../../pages/client/reports/ClientReportsPageHeader'
import { ClientReputationPageHeader } from '../../pages/client/reputation/ClientReputationPageHeader'
import { ClientRequestsPageHeader } from '../../pages/client/requests/ClientRequestsPageHeader'
import { ClientSettingsPageHeader } from '../../pages/client/settings/ClientSettingsPageHeader'
import { ClientServiceLinesPageHeader } from '../../pages/client/service-lines/ClientServiceLinesPageHeader'
import { ClientUpdatesPageHeader } from '../../pages/client/updates/ClientUpdatesPageHeader'
import { TeamTasksPageHeader } from '../../pages/team/tasks/TeamTasksPageHeader'
import { AccessDeniedPage } from '../../pages/system/access-denied/AccessDeniedPage'
import { AuthLayout } from '../layout/AuthLayout'
import { NAVIGATION_SCOPES } from './roleAccess'
import { ProtectedRoute } from './ProtectedRoute'
import {
  AdminClientAccessPageRoute,
  AdminClientActivityPageRoute,
  AdminClientFilesLinksPageRoute,
  AdminClientOverviewPageRoute,
  AdminClientPreviewPageRoute,
  AdminClientReportsDashboardsPageRoute,
  AdminClientRequestsPageRoute,
  AdminClientSubmittedRequestsPageRoute,
  AdminClientUpdatesPageRoute,
  AdminClientWorkReviewPageRoute,
  AdminClientsPageRoute,
  AdminClinicCompliancePageRoute,
  AdminClinicMetricsPageRoute,
  AdminClinicReportingPageRoute,
  AdminClinicReputationPageRoute,
  AdminClinicSetupPageRoute,
  AdminDashboardLinksPageRoute,
  AdminPerformanceDashboardEditorPageRoute,
  AdminPerformanceDashboardsPageRoute,
  AdminReportsPageRoute,
  AdminTasksPageRoute,
  AccountSettingsPageRoute,
  ClientActionNeededPageRoute,
  ClientCallsBookingsPageRoute,
  ClientComplianceApprovalsPageRoute,
  ClientDashboardPageRoute,
  ClientExecutivePerformancePageRoute,
  ClientFilesLinksPageRoute,
  ClientMonthlyStrategyPageRoute,
  ClientOverviewPageRoute,
  ClientPatientAcquisitionPageRoute,
  ClientPerformancePageRoute,
  ClientProjectsPageRoute,
  ClientReportsDashboardsPageRoute,
  ClientReportsPageRoute,
  ClientReputationPageRoute,
  ClientRequestsPageRoute,
  ClientSettingsPageRoute,
  ClientServiceLinesPageRoute,
  ClientUpdatesPageRoute,
  DentalGrowthReviewPageRoute,
  TeamTasksPageRoute,
  ClinicDailyOpsPageRoute,
  TeamClinicOperatorPageRoute,
} from './RoutePages'

function lazyNamed(loader, exportName) {
  return lazy(() => loader().then((module) => ({ default: module[exportName] })))
}

const BuildBoardPage = lazyNamed(() => import('../../pages/legacy/build-board/BuildBoardPage'), 'BuildBoardPage')
const CrmDashboardPage = lazyNamed(() => import('../../pages/legacy/crm-dashboard/CrmDashboardPage'), 'CrmDashboardPage')
const DailyActivitiesPage = lazyNamed(() => import('../../pages/legacy/daily-activities/DailyActivitiesPage'), 'DailyActivitiesPage')
const LandingPage = lazyNamed(() => import('../../pages/legacy/landing/LandingPage'), 'LandingPage')
const MarketingProcessPage = lazyNamed(() => import('../../pages/legacy/marketing-process/MarketingProcessPage'), 'MarketingProcessPage')
const MarketingReportsPage = lazyNamed(() => import('../../pages/legacy/marketing-reports/MarketingReportsPage'), 'MarketingReportsPage')

const LoadingFallback = () => <div className="p-6 text-ui text-text-muted">Loading...</div>
const CLIENT_PORTAL_ACCESS_AUDIENCES = [ACCESS_AUDIENCES.WORKSPACE_ADMIN, ACCESS_AUDIENCES.WORKSPACE_MEMBER]
const {
  AGENCY,
  CLIENT_PORTAL,
  TEAM_OPS,
} = NAVIGATION_SCOPES

export const routeDefinitions = [
  {
    path: '/',
    id: 'landing',
    label: 'Landing',
    layout: 'public',
    showInNav: false,
    element: <LandingPage />,
  },
  {
    path: '/accept-invite',
    id: 'accept-invite',
    label: 'Accept Invite',
    layout: 'auth',
    showInNav: false,
    element: <AcceptInvitePage />,
  },
  {
    path: '/login',
    id: 'login',
    label: 'Login',
    layout: 'auth',
    showInNav: false,
    element: <LoginPage />,
  },
  {
    path: '/access-denied',
    id: 'access-denied',
    label: 'Access Denied',
    layout: 'auth',
    showInNav: false,
    element: <AccessDeniedPage />,
  },
  {
    path: '/account/settings',
    id: 'account-settings',
    label: 'Account Settings',
    pageTitle: 'Account Settings',
    accessAudiences: [
      ACCESS_AUDIENCES.AGENCY_ADMIN,
      ACCESS_AUDIENCES.AGENCY_MEMBER,
      ACCESS_AUDIENCES.WORKSPACE_ADMIN,
      ACCESS_AUDIENCES.WORKSPACE_MEMBER,
    ],
    contentWidth: 'content',
    iconName: 'user',
    showInNav: false,
    element: <AccountSettingsPageRoute />,
  },
  {
    path: '/client/overview',
    id: 'client-overview',
    label: 'Overview',
    pageTitle: 'Client Overview',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    contentWidth: 'content',
    header: ClientOverviewPageHeader,
    iconName: 'layoutDashboard',
    navigationScope: CLIENT_PORTAL,
    navOrder: 10,
    element: <ClientOverviewPageRoute />,
  },
  {
    path: '/client/dashboard',
    id: 'client-dashboard',
    label: 'Dashboard',
    pageTitle: 'Marketing Dashboard',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    contentWidth: 'content',
    header: ClientDashboardPageHeader,
    showInNav: false,
    iconName: 'layoutDashboard',
    element: <ClientDashboardPageRoute />,
  },
  {
    path: '/client/executive-performance',
    id: 'client-executive-performance',
    label: 'Executive Performance',
    pageTitle: 'Executive Performance',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN, ACCESS_AUDIENCES.WORKSPACE_ADMIN, ACCESS_AUDIENCES.WORKSPACE_MEMBER],
    clientTypes: [CLIENT_TYPES.CLINIC],
    contentWidth: 'content',
    iconName: 'barChart',
    navigationAudiences: [ACCESS_AUDIENCES.WORKSPACE_ADMIN, ACCESS_AUDIENCES.WORKSPACE_MEMBER],
    navLabel: 'Executive',
    navigationScope: CLIENT_PORTAL,
    navOrder: 25,
    requiredCapabilities: [CLINIC_REPORTING_CAPABILITIES.EXECUTIVE_VIEW],
    element: <ClientExecutivePerformancePageRoute />,
  },
  {
    path: '/client/monthly-strategy',
    id: 'client-monthly-strategy',
    label: 'Monthly Strategy',
    pageTitle: 'Monthly Strategy',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN, ACCESS_AUDIENCES.WORKSPACE_ADMIN, ACCESS_AUDIENCES.WORKSPACE_MEMBER],
    clientTypes: [CLIENT_TYPES.CLINIC],
    contentWidth: 'content',
    iconName: 'dollarSign',
    navigationAudiences: [ACCESS_AUDIENCES.WORKSPACE_ADMIN, ACCESS_AUDIENCES.WORKSPACE_MEMBER],
    navigationScope: CLIENT_PORTAL,
    navOrder: 45,
    requiredCapabilities: [CLINIC_REPORTING_CAPABILITIES.MONTHLY_FINANCE_VIEW],
    element: <ClientMonthlyStrategyPageRoute />,
  },
  {
    path: '/client/growth-review',
    id: 'dental-growth-review',
    label: 'Dental Growth Review',
    pageTitle: 'Dental Growth Review',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN, ACCESS_AUDIENCES.AGENCY_MEMBER, ACCESS_AUDIENCES.WORKSPACE_ADMIN, ACCESS_AUDIENCES.WORKSPACE_MEMBER],
    clientTypes: [CLIENT_TYPES.CLINIC],
    contentWidth: 'content',
    iconName: 'target',
    navLabel: 'Dental Growth Review',
    navigationScope: CLIENT_PORTAL,
    navOrder: 23,
    requiredCapabilities: [CLINIC_REPORTING_CAPABILITIES.DENTAL_GROWTH_REVIEW_VIEW],
    element: <DentalGrowthReviewPageRoute />,
  },
  {
    path: '/client/action-needed',
    id: 'client-action-needed',
    label: 'Action Needed',
    pageTitle: 'Action Needed',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    contentWidth: 'content',
    header: ClientActionNeededPageHeader,
    iconName: 'bell',
    navigationScope: CLIENT_PORTAL,
    navOrder: 20,
    element: <ClientActionNeededPageRoute />,
  },
  {
    path: '/client/performance',
    id: 'client-performance',
    label: 'Performance',
    pageTitle: 'Performance Dashboard',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    contentWidth: 'content',
    header: ClientPerformancePageHeader,
    showInNav: false,
    iconName: 'barChart',
    element: <ClientPerformancePageRoute />,
  },
  {
    path: '/client/patient-acquisition',
    id: 'client-patient-acquisition',
    label: 'Patient Acquisition',
    pageTitle: 'Patient Acquisition',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    header: ClientPatientAcquisitionPageHeader,
    iconName: 'target',
    clientTypes: [CLIENT_TYPES.CLINIC],
    navigationScope: CLIENT_PORTAL,
    navGroup: {
      id: 'client-performance-group',
      label: 'Performance',
      iconName: 'barChart',
      order: 30,
    },
    navLabel: 'Acquisition',
    element: <ClientPatientAcquisitionPageRoute />,
  },
  {
    path: '/client/calls-bookings',
    id: 'client-calls-bookings',
    label: 'Calls & Bookings',
    pageTitle: 'Calls & Bookings',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    header: ClientCallsBookingsPageHeader,
    iconName: 'phone',
    clientTypes: [CLIENT_TYPES.CLINIC],
    navigationScope: CLIENT_PORTAL,
    navGroup: {
      id: 'client-performance-group',
      label: 'Performance',
      iconName: 'barChart',
      order: 30,
    },
    navLabel: 'Calls',
    element: <ClientCallsBookingsPageRoute />,
  },
  {
    path: '/client/projects',
    id: 'client-projects',
    label: 'Projects',
    pageTitle: 'Projects',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    contentWidth: 'content',
    header: ClientProjectsPageHeader,
    iconName: 'checkCircle2',
    excludeClientTypes: [CLIENT_TYPES.CLINIC],
    navigationScope: CLIENT_PORTAL,
    navOrder: 30,
    element: <ClientProjectsPageRoute />,
  },
  {
    path: '/client/service-lines',
    id: 'client-service-lines',
    label: 'Service Lines',
    pageTitle: 'Service Lines',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    contentWidth: 'content',
    header: ClientServiceLinesPageHeader,
    iconName: 'stethoscope',
    clientTypes: [CLIENT_TYPES.CLINIC],
    navigationScope: CLIENT_PORTAL,
    navGroup: {
      id: 'client-performance-group',
      label: 'Performance',
      iconName: 'barChart',
      order: 30,
    },
    navLabel: 'Services',
    element: <ClientServiceLinesPageRoute />,
  },
  {
    path: '/client/reputation',
    id: 'client-reputation',
    label: 'Reputation',
    pageTitle: 'Reputation',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    contentWidth: 'content',
    header: ClientReputationPageHeader,
    iconName: 'messageSquare',
    clientTypes: [CLIENT_TYPES.CLINIC],
    navigationScope: CLIENT_PORTAL,
    navGroup: {
      id: 'client-performance-group',
      label: 'Performance',
      iconName: 'barChart',
      order: 30,
    },
    element: <ClientReputationPageRoute />,
  },
  {
    path: '/client/compliance-approvals',
    id: 'client-compliance-approvals',
    label: 'Compliance',
    pageTitle: 'Compliance & Approvals',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    contentWidth: 'content',
    header: ClientComplianceApprovalsPageHeader,
    iconName: 'shieldCheck',
    clientTypes: [CLIENT_TYPES.CLINIC],
    navigationScope: CLIENT_PORTAL,
    navGroup: {
      id: 'client-resources-group',
      label: 'Resources',
      iconName: 'fileText',
      order: 60,
    },
    element: <ClientComplianceApprovalsPageRoute />,
  },
  {
    path: '/client/reports-dashboards',
    id: 'client-reports-dashboards',
    label: 'Reports',
    pageTitle: 'Reports & Dashboards',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    contentWidth: 'content',
    header: ClientReportsDashboardsPageHeader,
    iconName: 'barChart',
    navigationScope: CLIENT_PORTAL,
    navOrder: 40,
    element: <ClientReportsDashboardsPageRoute />,
  },
  {
    path: '/client/files-links',
    id: 'client-files-links',
    label: 'Files & Links',
    pageTitle: 'Files & Links',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    contentWidth: 'content',
    header: ClientFilesLinksPageHeader,
    iconName: 'fileText',
    navigationScope: CLIENT_PORTAL,
    navGroup: {
      id: 'client-resources-group',
      label: 'Resources',
      iconName: 'fileText',
      order: 60,
    },
    navLabel: 'Files',
    element: <ClientFilesLinksPageRoute />,
  },
  {
    path: '/client/requests',
    id: 'client-requests',
    label: 'Requests',
    pageTitle: 'Requests',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    contentWidth: 'content',
    header: ClientRequestsPageHeader,
    iconName: 'messageSquare',
    navigationScope: CLIENT_PORTAL,
    navOrder: 50,
    element: <ClientRequestsPageRoute />,
  },
  {
    path: '/client/updates',
    id: 'client-updates',
    label: 'Updates',
    pageTitle: 'Updates',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    contentWidth: 'content',
    header: ClientUpdatesPageHeader,
    iconName: 'clock',
    navigationScope: CLIENT_PORTAL,
    navGroup: {
      id: 'client-resources-group',
      label: 'Resources',
      iconName: 'fileText',
      order: 60,
    },
    element: <ClientUpdatesPageRoute />,
  },
  {
    path: '/client/settings',
    id: 'client-settings',
    label: 'Settings',
    pageTitle: 'Settings',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    contentWidth: 'content',
    header: ClientSettingsPageHeader,
    iconName: 'settings',
    navigationScope: CLIENT_PORTAL,
    navOrder: 70,
    element: <ClientSettingsPageRoute />,
  },
  {
    path: '/client/reports',
    id: 'client-reports',
    label: 'Reports',
    pageTitle: 'Monthly Reports',
    accessAudiences: CLIENT_PORTAL_ACCESS_AUDIENCES,
    contentWidth: 'content',
    header: ClientReportsPageHeader,
    showInNav: false,
    iconName: 'fileText',
    element: <ClientReportsPageRoute />,
  },
  {
    path: '/admin/clients',
    id: 'admin-clients',
    label: 'Accounts',
    pageTitle: 'Accounts',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    header: AdminClientsPageHeader,
    iconName: 'users',
    navigationScope: AGENCY,
    navOrder: 10,
    element: <AdminClientsPageRoute />,
  },
  {
    path: '/admin/tasks',
    id: 'admin-tasks',
    label: 'Tasks',
    pageTitle: 'Tasks',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    header: TeamTasksPageHeader,
    iconName: 'checkCircle2',
    navigationScope: AGENCY,
    navOrder: 20,
    element: <AdminTasksPageRoute />,
  },
  {
    path: '/admin/dashboard-links',
    id: 'admin-dashboard-links',
    label: 'Dashboards',
    pageTitle: 'Dashboard Links',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    header: AdminDashboardLinksPageHeader,
    iconName: 'layoutDashboard',
    navigationScope: AGENCY,
    navOrder: 50,
    element: <AdminDashboardLinksPageRoute />,
  },
  {
    path: '/admin/performance-dashboards',
    id: 'admin-performance-dashboards',
    label: 'Performance',
    pageTitle: 'Performance Dashboards',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    header: AdminPerformanceDashboardsPageHeader,
    iconName: 'barChart',
    navigationScope: AGENCY,
    navOrder: 60,
    element: <AdminPerformanceDashboardsPageRoute />,
  },
  {
    path: '/admin/performance-dashboard-editor',
    id: 'admin-performance-dashboard-editor',
    label: 'Performance Editor',
    pageTitle: 'Performance Dashboard Editor',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    header: AdminPerformanceDashboardEditorPageHeader,
    showInNav: false,
    iconName: 'barChart',
    element: <AdminPerformanceDashboardEditorPageRoute />,
  },
  {
    path: '/admin/reports',
    id: 'admin-reports',
    label: 'Reports',
    pageTitle: 'Reports',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    header: AdminReportsPageHeader,
    iconName: 'fileText',
    navigationScope: AGENCY,
    navOrder: 70,
    element: <AdminReportsPageRoute />,
  },
  {
    path: '/admin/client-preview',
    id: 'admin-client-preview',
    label: 'Published Workspace Overview Preview',
    pageTitle: 'Published Workspace Overview Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientOverviewPageHeader,
    showInNav: false,
    iconName: 'layoutDashboard',
    element: <AdminClientPreviewPageRoute />,
  },
  {
    path: '/admin/client-action-needed-preview',
    id: 'admin-client-action-needed-preview',
    label: 'Published Action Needed Preview',
    pageTitle: 'Published Action Needed Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientActionNeededPageHeader,
    showInNav: false,
    iconName: 'bell',
    element: <ClientActionNeededPageRoute />,
  },
  {
    path: '/admin/client-patient-acquisition-preview',
    id: 'admin-client-patient-acquisition-preview',
    label: 'Patient Acquisition Preview',
    pageTitle: 'Patient Acquisition Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientPatientAcquisitionPageHeader,
    showInNav: false,
    iconName: 'target',
    element: <ClientPatientAcquisitionPageRoute />,
  },
  {
    path: '/admin/client-calls-bookings-preview',
    id: 'admin-client-calls-bookings-preview',
    label: 'Calls & Bookings Preview',
    pageTitle: 'Calls & Bookings Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientCallsBookingsPageHeader,
    showInNav: false,
    iconName: 'phone',
    element: <ClientCallsBookingsPageRoute />,
  },
  {
    path: '/admin/client-reputation-preview',
    id: 'admin-client-reputation-preview',
    label: 'Reputation Preview',
    pageTitle: 'Reputation Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientReputationPageHeader,
    showInNav: false,
    iconName: 'messageSquare',
    element: <ClientReputationPageRoute />,
  },
  {
    path: '/admin/client-service-lines-preview',
    id: 'admin-client-service-lines-preview',
    label: 'Service Lines Preview',
    pageTitle: 'Service Lines Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientServiceLinesPageHeader,
    showInNav: false,
    iconName: 'stethoscope',
    element: <ClientServiceLinesPageRoute />,
  },
  {
    path: '/admin/client-compliance-approvals-preview',
    id: 'admin-client-compliance-approvals-preview',
    label: 'Compliance & Approvals Preview',
    pageTitle: 'Compliance & Approvals Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientComplianceApprovalsPageHeader,
    showInNav: false,
    iconName: 'shieldCheck',
    element: <ClientComplianceApprovalsPageRoute />,
  },
  {
    path: '/admin/client-projects-preview',
    id: 'admin-client-projects-preview',
    label: 'Published Projects Preview',
    pageTitle: 'Published Projects Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientProjectsPageHeader,
    showInNav: false,
    iconName: 'checkCircle2',
    element: <ClientProjectsPageRoute />,
  },
  {
    path: '/admin/client-reports-dashboards-preview',
    id: 'admin-client-reports-dashboards-preview',
    label: 'Published Reports & Dashboards Preview',
    pageTitle: 'Published Reports & Dashboards Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientReportsDashboardsPageHeader,
    showInNav: false,
    iconName: 'barChart',
    element: <ClientReportsDashboardsPageRoute />,
  },
  {
    path: '/admin/client-files-links-preview',
    id: 'admin-client-files-links-preview',
    label: 'Published Files & Links Preview',
    pageTitle: 'Published Files & Links Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientFilesLinksPageHeader,
    showInNav: false,
    iconName: 'fileText',
    element: <ClientFilesLinksPageRoute />,
  },
  {
    path: '/admin/client-requests-preview',
    id: 'admin-client-requests-preview',
    label: 'Published Requests Preview',
    pageTitle: 'Published Requests Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientRequestsPageHeader,
    showInNav: false,
    iconName: 'messageSquare',
    element: <ClientRequestsPageRoute />,
  },
  {
    path: '/admin/client-updates-preview',
    id: 'admin-client-updates-preview',
    label: 'Published Updates Preview',
    pageTitle: 'Published Updates Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientUpdatesPageHeader,
    showInNav: false,
    iconName: 'clock',
    element: <ClientUpdatesPageRoute />,
  },
  {
    path: '/admin/client-settings-preview',
    id: 'admin-client-settings-preview',
    label: 'Published Settings Preview',
    pageTitle: 'Published Settings Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientSettingsPageHeader,
    showInNav: false,
    iconName: 'settings',
    element: <ClientSettingsPageRoute />,
  },
  {
    path: '/admin/client-dashboard-preview',
    id: 'admin-client-dashboard-preview',
    label: 'Reports & Dashboards Preview',
    pageTitle: 'Reports & Dashboards Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientReportsDashboardsPageHeader,
    showInNav: false,
    iconName: 'layoutDashboard',
    element: <ClientReportsDashboardsPageRoute />,
  },
  {
    path: '/admin/client-performance-preview',
    id: 'admin-client-performance-preview',
    label: 'Reports & Dashboards Preview',
    pageTitle: 'Reports & Dashboards Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientReportsDashboardsPageHeader,
    showInNav: false,
    iconName: 'barChart',
    element: <ClientReportsDashboardsPageRoute />,
  },
  {
    path: '/admin/client-report-preview',
    id: 'admin-client-report-preview',
    label: 'Reports & Dashboards Preview',
    pageTitle: 'Reports & Dashboards Preview',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    contentWidth: 'content',
    header: ClientReportsDashboardsPageHeader,
    showInNav: false,
    iconName: 'fileText',
    element: <ClientReportsDashboardsPageRoute />,
  },
  {
    path: '/admin/clinic-compliance',
    id: 'admin-clinic-compliance',
    label: 'Clinic Compliance',
    pageTitle: 'Clinic Compliance',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'shieldCheck',
    element: <AdminClinicCompliancePageRoute />,
  },
  {
    path: '/admin/clinic-reputation',
    id: 'admin-clinic-reputation',
    label: 'Clinic Reputation',
    pageTitle: 'Clinic Reputation',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'messageSquare',
    element: <AdminClinicReputationPageRoute />,
  },
  {
    path: '/admin/clinic-metrics',
    id: 'admin-clinic-metrics',
    label: 'Clinic Metrics',
    pageTitle: 'Clinic Metrics',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'target',
    element: <AdminClinicMetricsPageRoute />,
  },
  {
    path: '/admin/clinic-reporting',
    id: 'admin-clinic-reporting',
    label: 'Clinic Reporting',
    pageTitle: 'Clinic Reporting',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    requiredCapabilities: [
      CLINIC_REPORTING_CAPABILITIES.REPORTING_IMPORT,
      CLINIC_REPORTING_CAPABILITIES.REPORTING_PUBLISH,
    ],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'barChart',
    element: <AdminClinicReportingPageRoute />,
  },
  {
    path: '/admin/clinic-setup',
    id: 'admin-clinic-setup',
    label: 'Clinic Setup',
    pageTitle: 'Clinic Setup',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'stethoscope',
    element: <AdminClinicSetupPageRoute />,
  },
  {
    path: '/admin/client-access',
    id: 'admin-client-access',
    label: 'Access',
    pageTitle: 'Client Access',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'users',
    element: <AdminClientAccessPageRoute />,
  },
  {
    path: '/admin/client-activity',
    id: 'admin-client-activity',
    label: 'Activity',
    pageTitle: 'Client Activity',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'clock',
    element: <AdminClientActivityPageRoute />,
  },
  {
    path: '/admin/client-files-links',
    id: 'admin-client-files-links',
    label: 'Files & Links',
    pageTitle: 'Files & Links',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'fileText',
    element: <AdminClientFilesLinksPageRoute />,
  },
  {
    path: '/admin/client-reports-dashboards',
    id: 'admin-client-reports-dashboards',
    label: 'Reports & Dashboards',
    pageTitle: 'Reports & Dashboards',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'barChart',
    element: <AdminClientReportsDashboardsPageRoute />,
  },
  {
    path: '/admin/client-requests',
    id: 'admin-client-requests',
    label: 'Actions',
    pageTitle: 'Action Needed',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'bell',
    element: <AdminClientRequestsPageRoute />,
  },
  {
    path: '/admin/client-submitted-requests',
    id: 'admin-client-submitted-requests',
    label: 'Requests',
    pageTitle: 'Client Requests',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'messageSquare',
    element: <AdminClientSubmittedRequestsPageRoute />,
  },
  {
    path: '/admin/client-updates',
    id: 'admin-client-updates',
    label: 'Updates',
    pageTitle: 'Client Updates',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'clock',
    element: <AdminClientUpdatesPageRoute />,
  },
  {
    path: '/admin/client-work-review',
    id: 'admin-client-work-review',
    label: 'Projects',
    pageTitle: 'Client Projects',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'eye',
    element: <AdminClientWorkReviewPageRoute />,
  },
  {
    path: '/admin/client-overview',
    id: 'admin-client-overview',
    label: 'Overview Editor',
    pageTitle: 'Client Overview Editor',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'fileText',
    element: <AdminClientOverviewPageRoute />,
  },
  {
    path: '/team/tasks',
    id: 'team-tasks',
    label: 'Team Tasks',
    pageTitle: 'Team Tasks',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_MEMBER],
    header: TeamTasksPageHeader,
    iconName: 'checkCircle2',
    navigationScope: TEAM_OPS,
    navOrder: 10,
    element: <TeamTasksPageRoute />,
  },
  {
    path: '/clinic/daily-ops',
    id: 'clinic-daily-ops',
    label: 'Daily Operations',
    pageTitle: 'Daily Operations',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN, ACCESS_AUDIENCES.AGENCY_MEMBER, ACCESS_AUDIENCES.WORKSPACE_ADMIN, ACCESS_AUDIENCES.WORKSPACE_MEMBER],
    contentWidth: 'content',
    iconName: 'phone',
    navigationScopes: [CLIENT_PORTAL, TEAM_OPS],
    navOrder: 40,
    requiredCapabilities: [CLINIC_REPORTING_CAPABILITIES.DAILY_OPS_VIEW],
    element: <ClinicDailyOpsPageRoute />,
  },
  {
    path: '/team/clinic-operator',
    id: 'team-clinic-operator',
    label: 'Clinic Operator',
    pageTitle: 'Clinic Operator',
    accessAudiences: [ACCESS_AUDIENCES.AGENCY_ADMIN, ACCESS_AUDIENCES.AGENCY_MEMBER],
    contentWidth: 'content',
    iconName: 'barChart',
    navigationScope: TEAM_OPS,
    navOrder: 30,
    requiredCapabilities: [CLINIC_REPORTING_CAPABILITIES.WEEKLY_OPERATOR_VIEW],
    element: <TeamClinicOperatorPageRoute />,
  },
  {
    path: '/legacy/build-board',
    id: 'legacy-build-board',
    label: 'Legacy Buildout',
    pageTitle: 'Legacy Buildout',
    showInNav: false,
    element: <BuildBoardPage />,
  },
  {
    path: '/legacy/crm-dashboard',
    id: 'legacy-crm-dashboard',
    label: 'Legacy CRM Dashboard',
    pageTitle: 'Legacy CRM Dashboard',
    showInNav: false,
    element: <CrmDashboardPage />,
  },
  {
    path: '/legacy/marketing-process',
    id: 'legacy-marketing-process',
    label: 'Legacy Marketing Processes',
    pageTitle: 'Legacy Marketing Processes',
    showInNav: false,
    element: <MarketingProcessPage />,
  },
  {
    path: '/legacy/daily-activities',
    id: 'legacy-daily-activities',
    label: 'Legacy Daily Activities',
    pageTitle: 'Legacy Daily Activities',
    showInNav: false,
    element: <DailyActivitiesPage />,
  },
  {
    path: '/legacy/marketing-reports',
    id: 'legacy-marketing-reports',
    label: 'Legacy Marketing Reports',
    pageTitle: 'Legacy Marketing Reports',
    showInNav: false,
    element: <MarketingReportsPage />,
  },
]

export const routeMetadata = routeDefinitions.map((route) => {
  const metadata = { ...route }
  delete metadata.element

  return metadata
})

function getRoutePath(path) {
  return path === '/' ? undefined : path.replace(/^\//, '')
}

function buildRouteElement(route) {
  const routeElement = route.layout === 'auth'
    ? <AuthLayout>{route.element}</AuthLayout>
    : <Suspense fallback={<LoadingFallback />}>{route.element}</Suspense>

  if (!route.accessAudiences?.length && !route.requiredCapabilities?.length) {
    return routeElement
  }

  return (
    <ProtectedRoute route={route}>
      {routeElement}
    </ProtectedRoute>
  )
}

export function createRouteChildren() {
  return routeDefinitions.map((route) => {
    const element = buildRouteElement(route)

    if (route.path === '/') {
      return { index: true, element }
    }

    return {
      path: getRoutePath(route.path),
      element,
    }
  })
}

