import { USER_ROLES } from '../../entities/profile'
import { AdminClientsPageHeader } from '../../pages/admin/clients/AdminClientsPageHeader'
import { AdminDashboardLinksPageHeader } from '../../pages/admin/dashboard-links/AdminDashboardLinksPageHeader'
import { AdminPerformanceDashboardEditorPageHeader } from '../../pages/admin/performance-dashboard-editor/AdminPerformanceDashboardEditorPageHeader'
import { AdminPerformanceDashboardsPageHeader } from '../../pages/admin/performance-dashboards/AdminPerformanceDashboardsPageHeader'
import { AdminReportsPageHeader } from '../../pages/admin/reports/AdminReportsPageHeader'
import { ClientDashboardPageHeader } from '../../pages/client/dashboard/ClientDashboardPageHeader'
import { ClientOverviewPageHeader } from '../../pages/client/overview/ClientOverviewPageHeader'
import { ClientPerformancePageHeader } from '../../pages/client/performance/ClientPerformancePageHeader'
import { ClientReportsPageHeader } from '../../pages/client/reports/ClientReportsPageHeader'
import { TeamTasksPageHeader } from '../../pages/team/tasks/TeamTasksPageHeader'

export const routeMetadata = [
  {
    path: '/',
    id: 'landing',
    label: 'Landing',
    layout: 'public',
    showInNav: false,
  },
  {
    path: '/accept-invite',
    id: 'accept-invite',
    label: 'Accept Invite',
    layout: 'auth',
    showInNav: false,
  },
  {
    path: '/login',
    id: 'login',
    label: 'Login',
    layout: 'auth',
    showInNav: false,
  },
  {
    path: '/access-denied',
    id: 'access-denied',
    label: 'Access Denied',
    layout: 'auth',
    showInNav: false,
  },
  {
    path: '/client/overview',
    id: 'client-overview',
    label: 'Overview',
    pageTitle: 'Client Overview',
    allowedRoles: [USER_ROLES.CLIENT_USER],
    header: ClientOverviewPageHeader,
    iconName: 'layoutDashboard',
  },
  {
    path: '/client/dashboard',
    id: 'client-dashboard',
    label: 'Dashboard',
    pageTitle: 'Marketing Dashboard',
    allowedRoles: [USER_ROLES.CLIENT_USER],
    header: ClientDashboardPageHeader,
    showInNav: false,
    iconName: 'layoutDashboard',
  },
  {
    path: '/client/performance',
    id: 'client-performance',
    label: 'Performance',
    pageTitle: 'Performance Dashboard',
    allowedRoles: [USER_ROLES.CLIENT_USER],
    header: ClientPerformancePageHeader,
    iconName: 'barChart',
  },
  {
    path: '/client/requests',
    id: 'client-requests',
    label: 'Requests',
    pageTitle: 'Client Requests',
    allowedRoles: [USER_ROLES.CLIENT_USER],
    showInNav: true,
    iconName: 'messageSquare',
  },
  {
    path: '/client/reports',
    id: 'client-reports',
    label: 'Reports',
    pageTitle: 'Monthly Reports',
    allowedRoles: [USER_ROLES.CLIENT_USER],
    header: ClientReportsPageHeader,
    showInNav: false,
    iconName: 'fileText',
  },
  {
    path: '/admin/clients',
    id: 'admin-clients',
    label: 'Clients',
    pageTitle: 'Clients',
    allowedRoles: [USER_ROLES.AGENCY_ADMIN],
    header: AdminClientsPageHeader,
    iconName: 'users',
  },
  {
    path: '/admin/tasks',
    id: 'admin-tasks',
    label: 'Tasks',
    pageTitle: 'Tasks',
    allowedRoles: [USER_ROLES.AGENCY_ADMIN],
    header: TeamTasksPageHeader,
    iconName: 'checkCircle2',
  },
  {
    path: '/admin/dashboard-links',
    id: 'admin-dashboard-links',
    label: 'Dashboards',
    pageTitle: 'Dashboard Links',
    allowedRoles: [USER_ROLES.AGENCY_ADMIN],
    header: AdminDashboardLinksPageHeader,
    iconName: 'layoutDashboard',
  },
  {
    path: '/admin/performance-dashboards',
    id: 'admin-performance-dashboards',
    label: 'Performance',
    pageTitle: 'Performance Dashboards',
    allowedRoles: [USER_ROLES.AGENCY_ADMIN],
    header: AdminPerformanceDashboardsPageHeader,
    iconName: 'barChart',
  },
  {
    path: '/admin/performance-dashboard-editor',
    id: 'admin-performance-dashboard-editor',
    label: 'Performance Editor',
    pageTitle: 'Performance Dashboard Editor',
    allowedRoles: [USER_ROLES.AGENCY_ADMIN],
    header: AdminPerformanceDashboardEditorPageHeader,
    showInNav: false,
    iconName: 'barChart',
  },
  {
    path: '/admin/reports',
    id: 'admin-reports',
    label: 'Reports',
    pageTitle: 'Reports',
    allowedRoles: [USER_ROLES.AGENCY_ADMIN],
    header: AdminReportsPageHeader,
    iconName: 'fileText',
  },
  {
    path: '/admin/client-preview',
    id: 'admin-client-preview',
    label: 'Client Preview',
    pageTitle: 'Client Preview',
    allowedRoles: [USER_ROLES.AGENCY_ADMIN],
    header: ClientOverviewPageHeader,
    showInNav: false,
    iconName: 'layoutDashboard',
  },
  {
    path: '/admin/client-dashboard-preview',
    id: 'admin-client-dashboard-preview',
    label: 'Dashboard Preview',
    pageTitle: 'Dashboard Preview',
    allowedRoles: [USER_ROLES.AGENCY_ADMIN],
    header: ClientDashboardPageHeader,
    showInNav: false,
    iconName: 'layoutDashboard',
  },
  {
    path: '/admin/client-performance-preview',
    id: 'admin-client-performance-preview',
    label: 'Performance Preview',
    pageTitle: 'Performance Preview',
    allowedRoles: [USER_ROLES.AGENCY_ADMIN],
    header: ClientPerformancePageHeader,
    showInNav: false,
    iconName: 'barChart',
  },
  {
    path: '/admin/client-report-preview',
    id: 'admin-client-report-preview',
    label: 'Report Preview',
    pageTitle: 'Report Preview',
    allowedRoles: [USER_ROLES.AGENCY_ADMIN],
    header: ClientReportsPageHeader,
    showInNav: false,
    iconName: 'fileText',
  },
  {
    path: '/admin/client-access',
    id: 'admin-client-access',
    label: 'Access',
    pageTitle: 'Client Access',
    allowedRoles: [USER_ROLES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'users',
  },
  {
    path: '/admin/client-activity',
    id: 'admin-client-activity',
    label: 'Activity',
    pageTitle: 'Client Activity',
    allowedRoles: [USER_ROLES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'clock',
  },
  {
    path: '/admin/client-requests',
    id: 'admin-client-requests',
    label: 'Requests',
    pageTitle: 'Client Requests',
    allowedRoles: [USER_ROLES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'messageSquare',
  },
  {
    path: '/admin/client-overview',
    id: 'admin-client-overview',
    label: 'Overview Editor',
    pageTitle: 'Client Overview Editor',
    allowedRoles: [USER_ROLES.AGENCY_ADMIN],
    showInNav: false,
    fullBleedContent: true,
    hidePageHeader: true,
    iconName: 'fileText',
  },
  {
    path: '/team/tasks',
    id: 'team-tasks',
    label: 'Team Tasks',
    pageTitle: 'Team Tasks',
    allowedRoles: [USER_ROLES.AGENCY_TEAM],
    header: TeamTasksPageHeader,
    iconName: 'checkCircle2',
  },
  {
    path: '/legacy/build-board',
    id: 'legacy-build-board',
    label: 'Legacy Buildout',
    pageTitle: 'Legacy Buildout',
    showInNav: false,
  },
  {
    path: '/legacy/crm-dashboard',
    id: 'legacy-crm-dashboard',
    label: 'Legacy CRM Dashboard',
    pageTitle: 'Legacy CRM Dashboard',
    showInNav: false,
  },
  {
    path: '/legacy/marketing-process',
    id: 'legacy-marketing-process',
    label: 'Legacy Marketing Processes',
    pageTitle: 'Legacy Marketing Processes',
    showInNav: false,
  },
  {
    path: '/legacy/daily-activities',
    id: 'legacy-daily-activities',
    label: 'Legacy Daily Activities',
    pageTitle: 'Legacy Daily Activities',
    showInNav: false,
  },
  {
    path: '/legacy/marketing-reports',
    id: 'legacy-marketing-reports',
    label: 'Legacy Marketing Reports',
    pageTitle: 'Legacy Marketing Reports',
    showInNav: false,
  },
]
