export {
  assertClinicAggregateRecord,
  CLINIC_ACQUISITION_CHANNEL_META,
  CLINIC_ACQUISITION_CHANNELS,
  CLINIC_PROFILE_SPECIALTIES,
  CLINIC_PROFILE_SPECIALTY_META,
  CLINIC_SERVICE_LINE_STATUSES,
  CLINIC_SERVICE_LINE_STATUS_META,
  normalizeClinicLocation,
  normalizeClinicProfile,
  normalizeClinicServiceLine,
  normalizeCallBookingMetric,
  normalizePatientAcquisitionSnapshot,
  normalizeReputationSnapshot,
} from './model'
